### ISSUE TITLE
MachineBackupManager Process failed. Exit code 255

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1163]
During investigation of dev servers I've found weird exceptions related to backup/restore

```2016-11-16 08:05:01,526[spaceRuntimes-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 595]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspace1j88lzp0mp16knij
2016-11-16 08:05:14,417[spaceManager-59]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 676]    - Workspace 'iedexmain:iedexmain' with id 'workspacegxqj9bhfaku34gzi' is being stopped by user 'activity-checker'
2016-11-16 08:05:14,418[spaceManager-59]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 744]    - Creating snapshot of workspace 'workspacegxqj9bhfaku34gzi', machines to snapshot: '1'
2016-11-16 08:05:19,567[spaceRuntimes-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 595]   - Launching 'org.eclipse.che.ssh' agent at workspace workspace1j88lzp0mp16knij
2016-11-16 08:05:19,654[spaceManager-58]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 635]    - Workspace 'iamleshiy7:wss' with id 'workspace1j88lzp0mp16knij' started by user 'iamleshiy7'
2016-11-16 08:05:51,424[spaceManager-59]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 765]    - Saving new snapshots metadata, workspace id 'workspacegxqj9bhfaku34gzi'
2016-11-16 08:05:51,555[spaceManager-59]  [ERROR] [c.c.m.b.MachineBackupManager 287]    - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The ECDSA host key for node2.nightly5.codenvy-stg.com has changed,
and the key for the corresponding IP address 172.30.22.202
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
d6:3d:7c:95:88:46:99:a3:6a:0c:d7:34:28:0b:9d:9d.
Please contact your system administrator.
Add correct host key in /home/codenvy/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/codenvy/.ssh/known_hosts:2
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The ECDSA host key for node2.nightly5.codenvy-stg.com has changed,
and the key for the corresponding IP address 172.30.22.202
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
d6:3d:7c:95:88:46:99:a3:6a:0c:d7:34:28:0b:9d:9d.
Please contact your system administrator.
Add correct host key in /home/codenvy/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/codenvy/.ssh/known_hosts:2
ECDSA host key for node2.nightly5.codenvy-stg.com has changed and you have requested strict checking.
Host key verification failed.
2016-11-16 08:05:51,556[spaceManager-59]  [ERROR] [c.c.m.b.MachineBackupManager 205]    - Process failed. Exit code 255
java.io.IOException: Process failed. Exit code 255
        at com.codenvy.machine.backup.MachineBackupManager.execute(MachineBackupManager.java:288) [codenvy-machine-hosted-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at com.codenvy.machine.backup.MachineBackupManager.backupWorkspace(MachineBackupManager.java:197) [codenvy-machine-hosted-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at com.codenvy.machine.backup.MachineBackupManager.backupWorkspaceAndCleanup(MachineBackupManager.java:164) [codenvy-machine-hosted-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at com.codenvy.machine.RemoteDockerNode.unbindWorkspace(RemoteDockerNode.java:150) [codenvy-machine-hosted-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:281) [che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1113) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1090) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:298) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:287) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStop$2(WorkspaceManager.java:690) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$215/1774016560.run(Unknown Source) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2016-11-16 08:05:51,557[spaceManager-59]  [ERROR] [c.c.machine.RemoteDockerNode 155]    - Backup of workspace workspacegxqj9bhfaku34gzi filesystem terminated on node2.nightly5.codenvy-stg.com node. Process failed. Exit code 255
org.eclipse.che.api.core.ServerException: Backup of workspace workspacegxqj9bhfaku34gzi filesystem terminated on node2.nightly5.codenvy-stg.com node. Process failed. Exit code 255
        at com.codenvy.machine.backup.MachineBackupManager.backupWorkspace(MachineBackupManager.java:207) ~[codenvy-machine-hosted-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at com.codenvy.machine.backup.MachineBackupManager.backupWorkspaceAndCleanup(MachineBackupManager.java:164) ~[codenvy-machine-hosted-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at com.codenvy.machine.RemoteDockerNode.unbindWorkspace(RemoteDockerNode.java:150) ~[codenvy-machine-hosted-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:281) [che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1113) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1090) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:298) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:287) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStop$2(WorkspaceManager.java:690) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$215/1774016560.run(Unknown Source) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45```

**Comment by skryzhny** [comment]
We shouldn't use `-o StrictHostKeyChecking=no` either. 
We (or admin of codenvy installation) need add corresponding key to known_hosts file in process of adding MachineNode.
Also we need to have clear error message that explains reason and possible way to resolve it dis[layed to the user.
And we need tests to cover that usecase.
