### ISSUE TITLE
DockerConnector exception "Could not kill running container"

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1164]
During investigation of dev servers I've found weird exceptions related to snapshotting

```2016-11-16 07:38:18,398[ted-scheduler-8]  [ERROR] [p.d.m.c.DockerContainerCleaner 115]  - Failed to delete unused container with 'id': '9b01651491536a41a7381fb6c4ee5362ea6d5a277c5ee47a41a08ab59503d532' and 'name': '/node1.nightly5.codenvy
-stg.com/workspacej1zz7qy01g03vp7u_machine8lwt9oyag7jwm10c_iedexmain_dev-machine'
org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Error response from daemon: Could not kill running container 9b01651491536a41a7381fb6c4ee5362ea6d5a277c5ee47a41a08ab5950
3d532, cannot remove - Container 9b01651491536a41a7381fb6c4ee5362ea6d5a277c5ee47a41a08ab59503d532 is paused. Unpause the container before stopping

        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1311) ~[che-plugin-docker-client-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.DockerConnector.removeContainer(DockerConnector.java:349) ~[che-plugin-docker-client-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerContainerCleaner.removeContainer(DockerContainerCleaner.java:112) [che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerContainerCleaner.cleanUp(DockerContainerCleaner.java:96) [che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerContainerCleaner.run(DockerContainerCleaner.java:76) [che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:43) [che-core-commons-schedule-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745)
        ```

**Comment by garagatyi** [comment]
It happens because of container in a very weird state. It is not possible to remove it using docker API. Probably happened because of restart of instance.

**Comment by skryzhny** [comment]
Had few paused containers on codenvy.io
I think we hit problem described here: https://github.com/docker/docker/issues/22643

Looks like it fixed in https://github.com/docker/containerd/commits/v0.2.3
So to fix it we need to update docker used for codenvy.io

**Comment by bmicklea** [comment]
fixed in my branch.
