### ISSUE TITLE
Unexpected behaviour of swarm

### ISSUE THREAD

**Issue by mmorhun** [codenvy/codenvy#1215]
After adding label to a node which turn on maintenance mode on it, a few minutes after we have errors like this:
```
Error: Error response from docker API, status: 500, message: Error: image eclipseche/workspaceqbkump84detb4cdg_machinemvk8hw1pgqxs1hm1_user_dev-machine not found
```
during 5-7 minutes. Many workspaces failed to start.
More, this can happens on any node and doesn't depend on node under maintenance. So, seems, that adding maintenance label is a start point only, but real reason of fails is unknown. That image really exists on a node (different from node under maintenance) and that is we got 500 error code instead of 404.
Also take into account, that maintenance constraint is always added independently of nodes labels.

**Reproduction Steps:**
Add `com.codenvy.node-state=maintenance` label to docker service on any node.
Unfortunately, we cannot reproduce it locally or on staging, but it happens on production.
It is a subtask how to reproduce it on staging.

**Expected behavior:**
After adding maintenance label to a node, other nodes should work correctly.

**Observed behavior:**
Error on workspace starting with 500 code and `image not found` message on many nodes. But when image really doesn't exist we have 404 code and message `no such image`.

**Codenvy version:** 5.0.0-M8-SNAPSHOT
**OS and version:** CentOS Linux 7 (Core) 3.10.0-327.10.1.el7.x86_64
**Docker version:** Version: 1.11.1 API version: 1.23
**Swarm:** Server Version: swarm/1.2.3

**Comment by garagatyi** [comment]
Looks like #880  is connected to this problem

**Comment by skryzhny** [comment]
This issue affect like 3%-5% of starting workspaces.
So then we start workspace there is chances (3%-5%) it can't start because of this.
In the same time this problem is about 85% cases when monitoring system calls me.
Please handle this issue at beginning of sprint.

**Comment by skryzhny** [comment]
```
2016-12-12 15:18:22,264[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 660]    - org.eclipse.che.api.core.ServerException: Start of environment wksp-z3i1 failed. Error: Error response from docker API, status: 500, message: Error: image eclipse-che/workspacethz78fqgpz8lriqf_machinezfiny67wsy8xjyog_qatestio_dev-machine not found

java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment wksp-z3i1 failed. Error: Error response from docker API, status: 500, message: Error: image eclipse-che/workspacethz78fqgpz8lriqf_machinezfiny67wsy8xjyog_qatestio_dev-machine not found

        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_45]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_45]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$4(WorkspaceManager.java:639) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$159/303085739.run(Unknown Source) [che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.eclipse.che.api.core.ServerException: Start of environment wksp-z3i1 failed. Error: Error response from docker API, status: 500, message: Error: image eclipse-che/workspacethz78fqgpz8lriqf_machinezfiny67wsy8xjyog_qatestio_dev-machine not found

        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:665) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:245) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$$Lambda$158/1742872442.call(Unknown Source) ~[na:na]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_45]
        ... 3 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error: image eclipse-che/workspacethz78fqgpz8lriqf_machinezfiny67wsy8xjyog_qatestio_dev-machine not found

        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:856) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:251) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:635) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        ... 7 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error: image eclipse-che/workspacethz78fqgpz8lriqf_machinezfiny67wsy8xjyog_qatestio_dev-machine not found

        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:947) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:791) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        ... 9 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error: image eclipse-che/workspacethz78fqgpz8lriqf_machinezfiny67wsy8xjyog_qatestio_dev-machine not found

        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:327) ~[che-plugin-docker-machine-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$17(CheEnvironmentEngine.java:764) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine$$Lambda$175/29274215.startMachine(Unknown Source) ~[na:na]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:894) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        ... 10 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Error: image eclipse-che/workspacethz78fqgpz8lriqf_machinezfiny67wsy8xjyog_qatestio_dev-machine not found

        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1324) ~[che-plugin-docker-client-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.plugin.docker.client.DockerConnector.createContainer(DockerConnector.java:1075) ~[che-plugin-docker-client-5.0.0-M8.jar:5.0.0-M8]
        at com.codenvy.swarm.client.SwarmDockerConnector.createContainer(SwarmDockerConnector.java:94) ~[codenvy-machine-hosted-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:525) ~[che-plugin-docker-machine-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:273) ~[che-plugin-docker-machine-5.0.0-M8.jar:5.0.0-M8]
        ... 13 common frames omitted
```

**Comment by mmorhun** [comment]
After applying of the workaround we observed some divergence in logs. Codenvy's logs don't report the problem any more, but seldom we still see in swarm logs double fails, which can means that the problem not fully workarounded. We could reproduce the issue for sure through swarm filter (maintenance constraints), but now we faced [another problem](https://github.com/codenvy/codenvy/issues/1211) with docker, which blocks us to check quckly whether the issue remains.

**Comment by mmorhun** [comment]
We ran additional tests and seems that our workaround works fine.
As about swarm logs, looks like it was swarm's internal stuff.

**Comment by bmicklea** [comment]
@mmorhun is this still an issue - it sounds like it's fixed.

**Comment by mmorhun** [comment]
@bmicklea Well, this issue was workarounded, not fixed. But seem that the problem is deep inside docker swarm.

**Comment by skryzhny** [comment]
Yes, we were forced to add another workaround after docker update to 17.04
https://github.com/codenvy/codenvy/issues/2144

**Comment by bmicklea** [comment]
So is this something we can fix?  Or are we waiting on a Swarm fix?

**Comment by mmorhun** [comment]
We already have workaround in our system which resolves the problem, but the real problem seems to be in swarm.

**Comment by TylerJewell** [comment]
We will not resolve this - instead moving to k8s.
