### ISSUE TITLE
Codenvy in Docker: Workspace delete fail

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1227]
This issue is happened only if workspace snapshotting is enabled during snapshot removal request to registry. 

**Reproduction Steps:**
1. Enable  snapshots.
2. Start and stop workspace
3. Delete workspace

**Expected behavior:**
Delete workspace without errors

**Observed behavior:**
<img width="1440" alt="2016-11-25 15 29 00" src="https://cloud.githubusercontent.com/assets/1614429/20626742/56e959ce-b324-11e6-970e-84334a3eaff3.png">
Response to this request
```
Request URL:http://172.19.20.18/api/workspace/workspace9d9sq36eb8tegeab
Request Method:DELETE
```

```
{message: "Transaction "rolled back" because transaction was set to RollbackOnly."}
```

Trace in logs
```
016-11-25 13:28:36,642[kspaceManager-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 772]    - Saving new snapshots metadata, workspace id 'workspace9d9sq36eb8tegeab'
2016-11-25 13:28:37,639[kspaceManager-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 704]    - Workspace 'admin:wksp-d33y' with id 'workspace9d9sq36eb8tegeab' stopped by user 'admin'
2016-11-25 13:28:57,828[nio-8080-exec-7]  [ERROR] [c.p.d.m.DockerInstanceProvider 168]  - An error occurred while deleting snapshot with url: http://172.19.20.18:5000/v2/machine_snapshot_pl59phfnpfru3apv/
manifests/sha256:cf9185a8b6742a5d16e7349d5a99d4a67bd3c4933270a87ed812d21b0462d59d
Error stream: {"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}

2016-11-25 13:28:57,833[nio-8080-exec-7]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 565]    - Internal server error occurs. Can't remove snapshot
org.eclipse.che.api.machine.server.exception.SnapshotException: Internal server error occurs. Can't remove snapshot
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.removeInstanceSnapshot(DockerInstanceProvider.java:171) ~[che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.removeSnapshot(CheEnvironmentEngine.java:527) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.removeSnapshot(WorkspaceRuntimes.java:489) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.removeSnapshots(WorkspaceManager.java:562) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceService.delete(WorkspaceService.java:277) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
```

**Comment by skabashnyuk** [comment]
Related to https://github.com/docker/distribution/issues/940
