### ISSUE TITLE
Failure to restore workspace from snapshot

### ISSUE THREAD

**Issue by mkuznyetsov** [codenvy/codenvy#1262]
This error occurs randomly and has no stable reproduce steps yet

During performance testing on nightly5.codenvy-stg.com at December 1 2016 at 12:07:51 UTC+2 there was a failed workspace startup.

Test plan was:
1. Create and start 10 workspaces.
2. Stop those workspaces simultaneoysly
3. Again start those workspaces.(here the error occured)
Do it with autosnapshot and autorestore enabled.

Error logs:

```
2016-12-01 10:07:51,452[spaceManager-30]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 660]    - org.eclipse.che.api.core.ServerException: Start of environment jmeter failed. Error: Error response from docker API,
 status: 500, message: Error: image eclipse-che/workspaceman7rfafsyurb0nt_machineerwn9pncisth4lsb_mkuznyetsov_ws-machine not found

java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment jmeter failed. Error: Error response from docker API, status: 500, message: Error: image eclipse-che/w
orkspaceman7rfafsyurb0nt_machineerwn9pncisth4lsb_mkuznyetsov_ws-machine not found

        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_45]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_45]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:639) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$174/468071201.run(Unknown Source) [che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.eclipse.che.api.core.ServerException: Start of environment jmeter failed. Error: Error response from docker API, status: 500, message: Error: image eclipse-che/workspaceman7rfafsyurb0nt_machi
neerwn9pncisth4lsb_mkuznyetsov_ws-machine not found

        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:665) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:245) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$$Lambda$173/1007906289.call(Unknown Source) ~[na:na]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_45]
        ... 3 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error: image eclipse-che/workspaceman7rfafsyurb0nt_machineerwn9pncisth4lsb_mkuznyetsov_ws-machine n
ot found

        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:856) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:251) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:635) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        ... 7 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error: image eclipse-che/workspaceman7rfafsyurb0nt_machineerwn9pncisth4lsb_mkuznyetsov_ws-machine n
ot found

        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:947) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:791) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        ... 9 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error: image eclipse-che/workspaceman7rfafsyurb0nt_machineerwn9pncisth4lsb_mkuznyetsov_ws-machine n
ot found

        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:327) ~[che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$9(CheEnvironmentEngine.java:764) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine$$Lambda$188/1662464104.startMachine(Unknown Source) ~[na:na]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:894) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        ... 10 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Error: image eclipse-che/workspaceman7rfafsyurb0nt_machineerwn9pncisth4lsb_mk
uznyetsov_ws-machine not found

        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1324) ~[che-plugin-docker-client-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.DockerConnector.createContainer(DockerConnector.java:1075) ~[che-plugin-docker-client-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at com.codenvy.swarm.client.SwarmDockerConnector.createContainer(SwarmDockerConnector.java:94) ~[codenvy-machine-hosted-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:525) ~[che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:273) ~[che-plugin-docker-machine-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
        ... 13 common frames omitted
```

**Comment by JamesDrummond** [comment]
Not currently reproducible. Waiting for another occurrence.

**Comment by bmicklea** [comment]
Dropping to P2 until we have another occurrence.

**Comment by skabashnyuk** [comment]
can't reproduce
