### ISSUE TITLE
Misleading error message about "Docker image build failed" when restore from snapshot failed

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1267]
It's hard to detect problem related to docker registry used for snapshots from error message:
`Codenvy codenvy.io error: o.e.c.a.w.s.WorkspaceManager - org.eclipse.che.api.core.ServerException: Start of environment 818cafe failed. Error: Docker image build failed. Image id not found in build output.`

**Reproduction Steps:**

Star workspace
Make snapshot of workspace
Stop workspace
Stop/block access to docker registry used for storing snapshots `service docker-distribution stop`
Start workspace

**Expected behavior:**

Clear message in logs that we have problems pulling images from docker registry
Maybe need to show dialog to user with choise to start workspace from recipe. 

**Observed behavior:**

See attached image

**Codenvy version:** 5.0.0-M7
**OS and version:** Centos 7.2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: No
Problem can be reliably reproduced: Yes
![failed-to-start-from snapshot](https://cloud.githubusercontent.com/assets/1636620/20798781/c945bb34-b7e8-11e6-878d-274212fab092.png)

**Comment by garagatyi** [comment]
It happens because we wrap pulling with building of image. It is needed to workaround some our issues with Swarm.

**Comment by skabashnyuk** [comment]
@skryzhny are you ok with explanation or you have other proposals?

**Comment by skryzhny** [comment]
No, I'm not OK.
I need to have information:
- If build was wrapped from pulling our repo, need to throw ERROR with stacktrace and clearly state in error message that we actually tried to restore from snapshot, and failed.
- If build was from user-supplied recipe then change from ERROR to WARN and don't print stacktrace.

```
2017-03-29 21:06:57,085[aceSharedPool-4]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 779]    - Docker image build failed. Image id not found in build output.
org.eclipse.che.api.core.ServerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1004) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:810) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.5.0.jar:5.5.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
Caused by: org.eclipse.che.api.core.ServerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:335) ~[che-plugin-docker-machine-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:782) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:946) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        ... 11 common frames omitted
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Docker image build failed. Image id not found in build output.
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:196) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.prepareImage(MachineProviderImpl.java:379) ~[che-plugin-docker-machine-5.5.0.jar:5.5.0]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:276) ~[che-plugin-docker-machine-5.5.0.jar:5.5.0]
        ... 13 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:829) ~[che-plugin-docker-client-5.5.0.jar:5.5.0]
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:752) ~[che-plugin-docker-client-5.5.0.jar:5.5.0]
        at com.codenvy.swarm.client.SwarmDockerConnector.buildImage(SwarmDockerConnector.java:88) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:179) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        ... 15 common frames omitted
```
Error message doesn't have iinformation important to me:
- WorkspaceID
- Environment
- Node on which build failed
- Probably recipe URL

**Comment by garagatyi** [comment]
Related to swarm. Won't be fixed.
