### ISSUE TITLE
Error Sync port is not exposed in ws-machine

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1333]
Got this error:
```
2016-12-12 14:02:42,933[spaceRuntimes-6]  [ERROR] [c.c.machine.RemoteDockerNode 155]    - Sync port is not exposed in ws-machine. Workspace projects syncing is not possible
org.eclipse.che.api.machine.server.exception.MachineException: Sync port is not exposed in ws-machine. Workspace projects syncing is not possible
	at com.codenvy.machine.RemoteDockerNode.getSyncPort(RemoteDockerNode.java:196) ~[codenvy-machine-hosted-5.0.0-M8.jar:5.0.0-M8]
	at com.codenvy.machine.RemoteDockerNode.unbindWorkspace(RemoteDockerNode.java:153) ~[codenvy-machine-hosted-5.0.0-M8.jar:5.0.0-M8]
	at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:281) [che-plugin-docker-machine-5.0.0-M8.jar:5.0.0-M8]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1117) [che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1094) [che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:298) [che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:651) [che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:245) [che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$$Lambda$142/797055125.call(Unknown Source) [che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) [che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Reproduction Steps:**

Start workspace from recipe without exposed ssh port and without ssh agent
like custom stack 
```
FROM centos
RUN echo rrwrre
```

WS-Config:
```
{
  "environments": {
    "wksp-centos3": {
      "machines": {
        "dev-machine": {
          "attributes": {
            "memoryLimitBytes": "2147483648"
          },
          "servers": {},
          "agents": [
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.terminal"
          ]
        }
      },
      "recipe": {
        "type": "dockerfile",
        "content": "FROM centos\nRUN echo rrerwe\n",
        "contentType": "text/x-dockerfile"
      }
    }
  },
  "defaultEnv": "wksp-centos3",
  "projects": [],
  "name": "wksp-centos3",
  "commands": [],
  "links": []
}
```

**Expected behavior:**

Normal workspace startup.

**Observed behavior:**

Workspace failed to start.

**Codenvy version:** 5.0.0-M8
**OS and version:** Centos 7.2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by garagatyi** [comment]
Fixed by #1371
