### ISSUE TITLE
Test Codenvy Dockerized with 1.10 Daemon

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#1341]
Our financial services accounts will only use the Docker version that is part of the standard distribution packages. Unfortunately, this is docker 1.10. They will not (TIAA) install a Docker 1.11 daemon to run Codenvy.  So we should perform system tests with a Docker 1.10 daemon to see if there are problems.

**Comment by riuvshin** [comment]
Codenvy does not work on docker `1.10.x`
Minimum working version is `1.11.0`

to reproduce issue please use following vagrantfile

```
box      = 'centos7.2'
url      = 'https://install.codenvycorp.com/centos7.2.box'

ram      = '8096'
cpus     = '4'
bridge   = 'eth0'

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_url = url
  config.ssh.insert_key = false
  config.vm.network :private_network, ip: "192.168.56.77"

config.vm.provider :virtualbox do |vbox|
    vbox.customize [
        'modifyvm', :id,
        '--memory', ram,
        '--cpus', cpus
    ]
 end
    config.vm.provision "shell", inline: "echo -e \"nameserver 8.8.8.8\n\" >> /etc/resolv.conf"
    config.vm.provision "shell", inline: "yum install docker -y"
    config.vm.provision "shell", inline: "iptables -I INPUT 1 -p tcp -m tcp --dport 80 -j ACCEPT"
    config.vm.provision "shell", inline: "iptables -I INPUT 1 -p tcp -m tcp --dport 23750 -j ACCEPT"
    config.vm.provision "shell", inline: "iptables -I INPUT 1 -p tcp -m tcp --dport 32768:65535 -j ACCEPT"
    config.vm.provision "shell", inline: "service docker start"
    config.vm.provision "shell", inline: "docker run -i --rm -v /var/run/docker.sock:/var/run/docker.sock -v /root/.codenvy:/data -v /root/.codenvy/backup:/backup codenvy/cli:nightly start"
end
```

**Comment by TylerJewell** [comment]
Let's leave open please.  I would like an analysis of why it does not work.  We have customers who cannot use 1.11 so we need to think on options.

**Comment by riuvshin** [comment]
@TylerJewell this issue is only to test if it works or not. we need other issue to investigate why it does not work for @garagatyi

**Comment by TylerJewell** [comment]
We will keep the same issue.  First we should display outputs with errors and then have discussion.  We can relabel and reassign if necessary.

**Comment by riuvshin** [comment]
Ok, let me know if I need to do something else here.

**Comment by TylerJewell** [comment]
Can you post the specific error that you encountered and where it happened (during boot, etc).  Thanks.

**Comment by riuvshin** [comment]
![fail_docker_1 10](https://cloud.githubusercontent.com/assets/1636732/21196569/bbb828be-c240-11e6-8be8-c1c7d5ac8c49.png)

trace:
```
2016-12-14 19:02:02,319[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 660]    - org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error res
ponse from docker API, status: 500, message: Error response from daemon: no such file or directory

java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error response from docker API, status: 500, message: Erro
r response from daemon: no such file or directory

        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_102]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_102]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:639) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error response from docker API, status: 500, message: Error response from daemon: no suc
h file or directory

        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:665) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:245) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
        ... 3 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error response from daemon: no such file or directory

        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:856) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPS
HOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:251) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:635) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        ... 6 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error response from daemon: no such file or directory

        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:947) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:791) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPS
HOT]
        ... 8 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error response from daemon: no such file or directory

        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:339) ~[che-plugin-docker-machine-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$9(CheEnvironmentEngine.java:764) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0
-M9-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:894) ~[che-core-api-workspace-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        ... 9 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Error response from daemon: no such file or directory

        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1324) ~[che-plugin-docker-client-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.DockerConnector.createContainer(DockerConnector.java:1075) ~[che-plugin-docker-client-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
        at com.codenvy.swarm.client.SwarmDockerConnector.createContainer(SwarmDockerConnector.java:94) ~[codenvy-machine-hosted-5.0.0-M9-SNAPSHOT.jar:5.0.0-M9-SNAPSHOT]
```

**Comment by TylerJewell** [comment]
@skabashnyuk - I see that you have this as part of your next sprint. I would like to ask that Alex spends <1/2 day to make an investigation.  If the investigation gives us clear answers, then we can discuss what our next steps are.  However, if we cannot find easy answers, then we will be ok with just requiring that Docker 1.11 as the minimum.  This is important, but don't think we have to make this an M9 requirement any more.

**Comment by mshaposhnik** [comment]
Running in vagrant with 1.10 version looks impossible - codenvy/cli image has a check for 1.11+ version.We need to skip this check in vagrant, is it possible ?

**Comment by TylerJewell** [comment]
Sorry @mshaposhnik - once it was determined that Docker 1.11 was required, I updated the CLI to force a fail if the daemon is <1.10.

I think - at this point, we can cancel & close this issue since we now know that the tests fail.  However, if you want to investigate what is involved with a backport to support 1.10, you would have to update the CLI to first work with 1.10:
1. In the che /dockerfiles/base/Dockerfile, you need to replace the Docker client with a 1.10 client.

You will then be allowed to run the CLI with a docker 1.10 daemon.

**Comment by garagatyi** [comment]
@TylerJewell [here ](https://github.com/codenvy/codenvy/issues/1341#issuecomment-267058266) you said that we should investigate why 1.10 doesn't work in this issue.
Are you OK now to close it?

**Comment by TylerJewell** [comment]
Well, the original issue was to perform a test. We have done the test and we got the error.  If we want to do a separate issue for investigating why the test failed and to make an assessment of engineering cost to backport, then we should probably create and track that as another issue .... or if you prefer to keep it in this issue, then re-title it with description of the work we will do now.

**Comment by garagatyi** [comment]
No, we with Roman thought exactly the same. So I'm +1 to that.

**Comment by TylerJewell** [comment]
+1 to what exactly?

**Comment by garagatyi** [comment]
To close this issue and open new one (if we need that) dedicated to engineering on why 1.10 doesn't work and how to fix that.

**Comment by TylerJewell** [comment]
ok.
