### ISSUE TITLE
Replace LOG.error with LOG.debug

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1358]
Got this error:
```
2016-12-15 08:10:40,965[ted-scheduler-8]  [ERROR] [c.a.s.WorkspaceActivityManager 124]  - Failed to stop the workspace
org.eclipse.che.api.core.ConflictException: Could not stop the workspace '11111:11111' because its status is 'SNAPSHOTTING'.
        at org.eclipse.che.api.workspace.server.WorkspaceManager.checkWorkspaceIsRunning(WorkspaceManager.java:820) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.stopWorkspace(WorkspaceManager.java:488) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.stopWorkspace(WorkspaceManager.java:464) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at com.codenvy.activity.server.WorkspaceActivityManager.invalidate(WorkspaceActivityManager.java:120) ~[codenvy-hosted-workspace-activity-5.0.0-M8.jar:5.0.0-M8]
        at sun.reflect.GeneratedMethodAccessor294.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:53) [che-core-commons-schedule-5.0.0-M8.jar:5.0.0-M8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```
We need to check status before attempting to stop it.
Probably we need to check it on API level additionally to checks in dashboard and IDE.

For 2 days I had 5 exceptions:
`# grep -c "because its status is 'SNAPSHOTTING'." catalina.out
5
`
Also please consider changing loglevel to WARNING and don't print stacktrace.

**Reproduction Steps:**

Don't know

**Expected behavior:**

No errors, check state of container before issuing command.

**Observed behavior:**

Errors in log.

**Codenvy version:** 5.0.0-M8
**OS and version:** Centos 7.2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: No
Problem can be reliably reproduced: Yes

**Comment by gazarenkov** [comment]
Agree, it is not a ERROR but I doubt we need a WARNING about it, just DEBUG, it looks like a normal situation so it depends on client logic how to process it. 
It should just reasonable react - like notify user that snapshotting is in progress, so he(she) should wait for some time (I believe client can be notified when it is done)

**Comment by bmicklea** [comment]
Closing as PR was merged.
