### ISSUE TITLE
Error: Couldn't create a snapshot of workspace

### ISSUE THREAD

**Issue by gc-alexlong** [codenvy/codenvy#1503]
Errors occurred during the shutdown of my local workspace. And while trying to create a snapshot, I see the same errors, plus additional about Codenvy being unable to create a snapshot. However, any changes made to the workspace, project files included, were actually saved.

**Reproduction Steps:**
1. I created a PHP project based on one of the sample projects, ran the test script successfully.
2. When I tried to stop the workspace, I saw a lot of errors, "Info Parsing file nn/nnn...". 
3. I started the workspace again, Codenvy states that workspace loaded successfully.
4. Created a new PHP file in project.
5. Clicked on Workspace view, clicked "Machine" > "Create Snapshot".
6. Same errors that occurred when stopping workspace occur here (Info Parsing...). Error about not creating a snapshot is logged.
7. Restarted workspace, changes made to workspace and project are still available.
8. Confirmed workspace changes being saved after restarting Docker container.

**Codenvy version:**    Codenvy Nightly

**OS and version:**    MacOS 10.11.6 (El Capitan)

**Docker version:** 1.12  

**Codenvy cli.log output:**  
2017-01-10 16:10:39,722[aceSharedPool-1] [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 762] - Creating snapshot of workspace 'workspaceooz1mm157jz0a78y', machines to snapshot: '1'
2017-01-10 16:10:55,618[aceSharedPool-1] [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 445] - Couldn't create a snapshot of workspace 'workspaceooz1mm157jz0a78y'
org.eclipse.che.api.machine.server.exception.MachineException: org.eclipse.che.plugin.docker.client.exception.DockerException: Docker image pushing failed. Cause: Get https://192.168.65.2:5000/v1/_ping: http: server gave HTTP response to HTTPS client
at org.eclipse.che.plugin.docker.machine.DockerInstance.saveToSnapshot(DockerInstance.java:243) ~[che-plugin-docker-machine-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
at org.eclipse.che.api.environment.server.CheEnvironmentEngine.saveSnapshot(CheEnvironmentEngine.java:502) ~[che-core-api-workspace-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.snapshotAndUpdateStatus(WorkspaceRuntimes.java:766) ~[che-core-api-workspace-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$snapshotAsync$2(WorkspaceRuntimes.java:443) ~[che-core-api-workspace-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Docker image pushing failed. Cause: Get https://192.168.65.2:5000/v1/_ping: http: server gave HTTP response to HTTPS client
at org.eclipse.che.plugin.docker.client.DockerConnector.push(DockerConnector.java:953) ~[che-plugin-docker-client-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
at org.eclipse.che.plugin.docker.machine.DockerInstance.saveToSnapshot(DockerInstance.java:233) ~[che-plugin-docker-machine-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
... 8 common frames omitted

**Comment by TylerJewell** [comment]
@skryzhny - is this related to the recent infrsatructure issue that you uncovered?

**Comment by gbatalski** [comment]
Please take a look at http://stackoverflow.com/questions/38695515/can-not-pull-push-images-after-update-docker-to-1-12%5D

at least on ubuntu this was the solution

Create or modify **/etc/docker/daemon.json** on the client machine with following content (in your case):
>
>{ "insecure-registries":["192.168.65.2:5000"] }
>
Restart docker daemon

**Comment by gc-alexlong** [comment]
I added that setting in Docker for Mac's settings. In the interface, no error popped up, and the "saving workspace" message eventually faded away. In the log, however, these were logged:

`2017-01-11 21:41:50,683[ckupScheduler-4]  [ERROR] [m.b.WorkspaceFsBackupScheduler 112]  - Backup of workspace workspaceavh6cmwoheyk2pz0 filesystem terminated due to timeout on 192.168.65.2 node.
org.eclipse.che.api.core.ServerException: Backup of workspace workspaceavh6cmwoheyk2pz0 filesystem terminated due to timeout on 192.168.65.2 node.
	at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:366) ~[codenvy-machine-hosted-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
	at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:245) ~[codenvy-machine-hosted-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
	at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:145) ~[codenvy-machine-hosted-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
	at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) ~[codenvy-machine-hosted-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]`

`2017-01-11 21:46:34,645[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 785]   - Saving new snapshots metadata, workspace id 'workspaceavh6cmwoheyk2pz0'`

**Comment by eivantsov** [comment]
@gc-alexlong I have got the same on a Linux node. Investigating.

**Comment by eivantsov** [comment]
![image](https://cloud.githubusercontent.com/assets/5337267/21930129/13bc0008-d99d-11e6-89c3-091a6780b798.png)
Can you configure your Docker for Mac this way?

**Comment by gc-alexlong** [comment]
The below is how it looks right now, I'll add the entry for localhost to see if that helps, too.

![screen shot 2017-01-13 at 8 15 16 am](https://cloud.githubusercontent.com/assets/19917397/21932937/af60f03e-d968-11e6-8e59-998d75c0c2f4.png)

**Comment by eivantsov** [comment]
You may try pushing manually without having to run and stop Codenvy workspaces. Just follow docs - https://docs.docker.com/registry/

**Comment by TylerJewell** [comment]
@gc-alexlong - this issue is a bit old.  Closing on the assumption that it was resolved.  Ok to keep posting here and then we can consider reopening.
