### ISSUE TITLE
Codenvy can't access registry if deployed on AWS and DNS uses external IP

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1572]
When deployed on AWS and DNS pointing to external IP codenvy tomcat can't access registry used for storing snapshots.
So it can't delete unused old snapshots after new ones pushed to registry.
Need to introduce new property used for communication between codenvy and registry containers, by default it should be name of registry container.

**Reproduction Steps:**
Lanch dockerized codenvy 5.1.0 on AWS and use external IP of instance in DNS
See errors in codenvy logs about inability connect to registry.
```
2017-01-18 20:18:41,638[ceSharedPool-14]  [ERROR] [c.p.d.m.DockerInstanceProvider 177]  - connect timed out
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_102]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_102]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_102]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_102]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_102]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_102]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_102]
        at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_102]
        at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_102]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[na:1.8.0_102]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_102]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_102]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[na:1.8.0_102]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_102]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_102]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_102]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.removeInstanceSnapshot(DockerInstanceProvider.java:162) ~[che-plugin-docker-machine-5.0.1.jar:5.0.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.removeSnapshot(CheEnvironmentEngine.java:527) [che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.removeBinaries(WorkspaceRuntimes.java:465) [che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.removeBinaries(WorkspaceRuntimes.java:482) [che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.snapshotAndUpdateStatus(WorkspaceRuntimes.java:792) [che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.snapshot(WorkspaceRuntimes.java:427) [che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$2(WorkspaceManager.java:667) [che-core-api-workspace-5.0.1.jar:5.0.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.1.jar:5.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
```
**Codenvy version:**  5.1.0

**Comment by riuvshin** [comment]
as we agreed we will add feature which will allow us to set extra hosts for codenvy containers, this way we will be able to set proper IPs for some DNS names.
