### ISSUE TITLE
Error org.eclipse.persistence.exceptions.DatabaseException

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1588]
I got several such errors:
```
2017-01-20 18:45:16,438[aceSharedPool-7]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 759]    - Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 7515 waits for ShareLock on transaction 52002; blocked by process 7011.
Process 7011 waits for ShareLock on transaction 52003; blocked by process 7515.
  Hint: See server log for query details.
  Where: while deleting tuple (1108,123) in relation "projectconfig"
Error Code: 0
Call: DELETE FROM projectconfig WHERE (id = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery(ProjectConfigImpl{id=5360429, path='/Spring', name='Spring', type='maven', description='null', source=SourceStorageImpl{id=5360430, type='git', location='https://github.com/codenvy-templates/web-spring-java-simple.git', parameters={branch=3.1.0, keepVcs=false}}, mixins=[], attributes={}})
org.eclipse.che.api.core.ServerException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 7515 waits for ShareLock on transaction 52002; blocked by process 7011.
Process 7011 waits for ShareLock on transaction 52003; blocked by process 7515.
  Hint: See server log for query details.
  Where: while deleting tuple (1108,123) in relation "projectconfig"
Error Code: 0
Call: DELETE FROM projectconfig WHERE (id = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery(ProjectConfigImpl{id=5360429, path='/Spring', name='Spring', type='maven', description='null', source=SourceStorageImpl{id=5360430, type='git', location='https://github.com/codenvy-templates/web-spring-java-simple.git', parameters={branch=3.1.0, keepVcs=false}}, mixins=[], attributes={}})
	at org.eclipse.che.api.workspace.server.jpa.JpaWorkspaceDao.update(JpaWorkspaceDao.java:84) ~[che-core-api-workspace-5.1.0.jar:5.1.0]
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$2(WorkspaceManager.java:751) ~[che-core-api-workspace-5.1.0.jar:5.1.0]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.1.0.jar:5.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 7515 waits for ShareLock on transaction 52002; blocked by process 7011.
Process 7011 waits for ShareLock on transaction 52003; blocked by process 7515.
  Hint: See server log for query details.
  Where: while deleting tuple (1108,123) in relation "projectconfig"
Error Code: 0
Call: DELETE FROM projectconfig WHERE (id = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery(ProjectConfigImpl{id=5360429, path='/Spring', name='Spring', type='maven', description='null', source=SourceStorageImpl{id=5360430, type='git', location='https://github.com/codenvy-templates/web-spring-java-simple.git', parameters={branch=3.1.0, keepVcs=false}}, mixins=[], attributes={}})
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:879) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.che.api.workspace.server.jpa.JpaWorkspaceDao.doUpdate(JpaWorkspaceDao.java:219) ~[che-core-api-workspace-5.1.0.jar:5.1.0]
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:70) ~[guice-persist-4.1.0.jar:na]
	at org.eclipse.che.api.workspace.server.jpa.JpaWorkspaceDao.update(JpaWorkspaceDao.java:78) ~[che-core-api-workspace-5.1.0.jar:5.1.0]
	... 5 common frames omitted
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 7515 waits for ShareLock on transaction 52002; blocked by process 7011.
Process 7011 waits for ShareLock on transaction 52003; blocked by process 7515.
  Hint: See server log for query details.
  Where: while deleting tuple (1108,123) in relation "projectconfig"
Error Code: 0
Call: DELETE FROM projectconfig WHERE (id = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery(ProjectConfigImpl{id=5360429, path='/Spring', name='Spring', type='maven', description='null', source=SourceStorageImpl{id=5360430, type='git', location='https://github.com/codenvy-templates/web-spring-java-simple.git', parameters={branch=3.1.0, keepVcs=false}}, mixins=[], attributes={}})
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1620) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:900) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:964) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:633) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2055) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:306) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.deleteObject(DatasourceCallQueryMechanism.java:210) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.deleteObject(StatementQueryMechanism.java:104) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.queries.DeleteObjectQuery.executeDatabaseQuery(DeleteObjectQuery.java:218) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:803) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.queries.DeleteObjectQuery.executeInUnitOfWorkObjectLevelModifyQuery(DeleteObjectQuery.java:119) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1790) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.CommitManager.deleteAllObjects(CommitManager.java:342) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.CommitManager.deleteAllObjects(CommitManager.java:296) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1444) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithPreBuiltChangeSet(UnitOfWorkImpl.java:1587) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:455) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:874) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	... 8 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 7515 waits for ShareLock on transaction 52002; blocked by process 7011.
Process 7011 waits for ShareLock on transaction 52003; blocked by process 7515.
  Hint: See server log for query details.
  Where: while deleting tuple (1108,123) in relation "projectconfig"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[tomcat-dbcp.jar:8.0.38]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[tomcat-dbcp.jar:8.0.38]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:892) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	... 33 common frames omitted
```

**Reproduction Steps:**
Don't know

**Codenvy version:**  5.1.0
**OS and version:**    Centos 7.3

**Docker version:** 1.12.5

**Comment by TylerJewell** [comment]
Applying P1 severity for now - it seems like it could be system destabilizing at some point.

**Comment by skabashnyuk** [comment]
Applying P2 - it's very rare exception.
