### ISSUE TITLE
ERROR: [DockerEnvironmentBackupManager 340]  - Process failed. Exit code 255

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1662]
We have CI task that periodically checks by launching predefined factory.
It work stable but today I got 2 calls from monitoring system.
```
2017-01-31 13:47:26,981[o-8080-exec-126]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 823]    - Workspace 'iedexmain:wss_1' with id 'workspacezt9lvn4y446uwy98' created by user 'iedexmain'
...
2017-01-31 13:47:35,828[ceSharedPool-12]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 664]   - Launching 'org.eclipse.che.terminal' agent at workspace workspacezt9lvn4y446uwy98
...
2017-01-31 13:47:38,029[ceSharedPool-12]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 664]   - Launching 'org.eclipse.che.ssh' agent at workspace workspacezt9lvn4y446uwy98
...
2017-01-31 13:47:38,396[ceSharedPool-12]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 664]   - Launching 'com.codenvy.rsync_in_machine' agent at workspace workspacezt9lvn4y446uwy98
2017-01-31 13:47:38,728[ceSharedPool-12]  [ERROR] [DockerEnvironmentBackupManager 540]  - Error occurred during backup/restore on 'node9.codenvy.io' : Warning: Permanently added '[node9.codenvy.io]:35292,[172.30.12.109]:35292' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]
2017-01-31 13:47:38,729[ceSharedPool-12]  [ERROR] [DockerEnvironmentBackupManager 340]  - Process failed. Exit code 255
java.io.IOException: Process failed. Exit code 255
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:541) [codenvy-machine-hosted-5.1.2.jar:5.1.2]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreBackupInsideLock(DockerEnvironmentBackupManager.java:329) [codenvy-machine-hosted-5.1.2.jar:5.1.2]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreWorkspaceBackup(DockerEnvironmentBackupManager.java:216) [codenvy-machine-hosted-5.1.2.jar:5.1.2]
        at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:91) [codenvy-machine-hosted-5.1.2.jar:5.1.2]
        at com.codenvy.machine.agent.launcher.ExternalRsyncAgentLauncherImpl.launch(ExternalRsyncAgentLauncherImpl.java:68) [codenvy-machine-hosted-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:667) [che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1029) [che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:806) [che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:260) [che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:686) [che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:107) [che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:952) [che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:916) [che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) [che-core-commons-lang-5.1.2.jar:5.1.2]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2017-01-31 13:47:38,787[ceSharedPool-12]  [WARN ] [DockerEnvironmentBackupManager 293]  - Attempt to backup workspace workspacezt9lvn4y446uwy98 after cleanup
```

Side node: we need to add more info to logs that may help to diagnose the issue.

**Reproduction Steps:**

Don't know

**Codenvy version:**    5.1.2

**OS and version:**    Centos 7.2

**Docker version:** 1.12.5

**Comment by bmicklea** [comment]
@skryzhny please label these issues with `kind/bug` and `severity/blocker`

**Comment by garagatyi** [comment]
Please provide factory url or json

**Comment by garagatyi** [comment]
We don't have enough information to investigate the reason of that error. I created [PR](https://github.com/codenvy/codenvy/pull/1735) that allows to log more information for such cases.

**Comment by garagatyi** [comment]
PR is merged. I'm closing the issue. @skryzhny Please increase logging level on prod when this version of codenvy is shipped to get more information for investigation in case this error occurs again.
