### ISSUE TITLE
NPE in logs: [o.e.c.a.c.n.EventService 108]        - null java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1705]
Got this in logs when performing graceful shutdown:
```
2017-02-06 12:27:07,617[aceSharedPool-8]  [ERROR] [o.e.c.a.c.n.EventService 108]        - null
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106) ~[na:1.8.0_102]
        at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097) ~[na:1.8.0_102]
        at com.codenvy.auth.sso.client.SessionStore.removeSessionByToken(SessionStore.java:58) ~[codenvy-hosted-sso-client-5.2.1.jar:5.2.1]
        at com.codenvy.auth.sso.client.MachineSessionInvalidator.onEvent(MachineSessionInvalidator.java:55) ~[codenvy-hosted-sso-client-5.2.1.jar:5.2.1]
        at com.codenvy.auth.sso.client.MachineSessionInvalidator.onEvent(MachineSessionInvalidator.java:35) ~[codenvy-hosted-sso-client-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:106) ~[che-core-api-core-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stopEnvironmentAndPublishEvents(WorkspaceRuntimes.java:816) [che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:368) [che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$3(WorkspaceManager.java:813) [che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.2.1.jar:5.2.1]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
```

**Reproduction Steps:**

Don't know, maybe need more info in logs.

**Codenvy version:**    5.2.1

**OS and version:**    Centos 7.3

**Docker version:** 1.12.5

**Comment by skryzhny** [comment]
Also got bunch of exceptions:
```
2017-02-06 12:27:56,620[aceSharedPool-8]  [ERROR] [o.e.c.a.c.n.EventService 108]        - null
java.lang.NullPointerException: null
2017-02-06 12:27:56,689[ceSharedPool-12]  [ERROR] [o.e.c.a.c.n.EventService 108]        - null
java.lang.NullPointerException: nul
```

**Comment by eivantsov** [comment]
@skryzhny is this still an issue?

**Comment by skryzhny** [comment]
No, I haven't seen that issue for 2 months.

**Comment by eivantsov** [comment]
I'm closing the issue then. We may reopen or create a new one if smth like that shows up in logs again.
