### ISSUE TITLE
Exceptions when performin codnvy stop

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1707]
Got this error when performing stop:
```
2017-02-06 12:26:53,167[aceSharedPool-8]  [WARN ] [c.c.machine.RemoteDockerNode 101]    - The container '5e8dac86d5542d4d7b6bb4f7f7f6af76860001a97733f27fadc732c631b6c008' in the workspace 'workspace******************************' won't be backed up. Th
e reason is that the workspace wasn't restored from backup
2017-02-06 12:26:54,232[aceSharedPool-8]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 774]    - Could not perform operation because application server is stopping
org.eclipse.che.api.core.ServerException: Could not perform operation because application server is stopping
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:994) ~[che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:800) ~[che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:260) ~[che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:712) ~[che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:105) ~[che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:977) [che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:941) [che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.2.1.jar:5.2.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: org.eclipse.che.api.core.ServerException: Could not perform operation because application server is stopping
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.ensurePreDestroyIsNotExecuted(CheEnvironmentEngine.java:1240) ~[che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.replaceMachine(CheEnvironmentEngine.java:1084) ~[che-core-api-workspace-5.2.1.jar:5.2.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:948) ~[che-core-api-workspace-5.2.1.jar:5.2.1]
        ... 11 common frames omitted
2017-02-06 12:26:58,680[pScheduler-6064]  [ERROR] [DockerEnvironmentBackupManager 373]  - null
java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method) ~[na:1.8.0_102]
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:412) ~[na:1.8.0_102]
        at org.eclipse.che.api.core.util.ProcessUtil.executeAndWait(ProcessUtil.java:117) ~[che-core-api-core-5.2.1.jar:5.2.1]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:537) [codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:368) [codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:249) [codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:149) [codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) [codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
2017-02-06 12:26:58,681[pScheduler-6064]  [ERROR] [m.b.WorkspaceFsBackupScheduler 112]  - Backup of workspace workspace6fwxpmy7rzbkiego filesystem interrupted on node1.codenvy.io node.
org.eclipse.che.api.core.ServerException: Backup of workspace workspace6fwxpmy7rzbkiego filesystem interrupted on node1.codenvy.io node.
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:374) ~[codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:249) ~[codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:149) ~[codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) ~[codenvy-machine-hosted-5.2.1.jar:5.2.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
2017-02-06 12:26:58,687[ost-startStop-2]  [INFO ] [o.e.c.a.s.server.SystemManager 93]   - Preparing system to shutdown
2017-02-06 12:26:58,695[ost-startStop-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 681]    - Shutting down workspace service
2017-02-06 12:26:58,710[ceSharedPool-12]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 783]    - Workspace '*****:wksp-***' with id 'workspace*****************' is being stopped by user 'undefined'
```

**Reproduction Steps:**
- Start 20-30 workspaces
- Perform codenvy stop via CLI

**Codenvy version:**  5.2.1

**OS and version:**   Centos 7.3 

**Docker version:** 1.12.5

**Comment by bmicklea** [comment]
Marking this as a P1 because it appears a workspace was not backed up which is a big deal. Two questions:
1. Has this occurred before?
2. Did this only affect one workspace or several?

**Comment by skryzhny** [comment]
It was occurred before but it was expected as we haven't  graceful stop, so I used workaround for it.
Issue is https://github.com/codenvy/codenvy/issues/1708
It affected only 3 workspaces at that time, but it depends on how many active workspaces we have in time of stop.
