### ISSUE TITLE
Errors in logs '[o.e.c.a.p.s.ProjectManager 131]      - User limit of inotify watches reached'

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1723]
Investigating unusually high activity fount thus in machines logs:

```
[STDOUT] 2017-02-07 17:21:13,745[ost-startStop-1]  [WARN ] [e.c.p.m.s.c.c.ClasspathManager 87]   - Maven server not started looks like you don't have Maven in your path
[STDOUT] Tue Feb 07 17:21:14 UTC 2017 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2017-02-07 17:21:16,971[ost-startStop-1]  [ERROR] [o.e.c.a.p.s.ProjectManager 131]      - User limit of inotify watches reached
[STDOUT] java.io.IOException: User limit of inotify watches reached
[STDOUT]        at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264) ~[na:1.8.0_65]
[STDOUT]        at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260) ~[na:1.8.0_65]
[STDOUT]        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329) ~[na:1.8.0_65]
[STDOUT]        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
[STDOUT] 2017-02-07 17:21:19,626[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 41,642 ms
[STDOUT] 2017-02-07 17:21:19,653[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-02-07 17:21:19,689[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 42283 ms
[STDOUT] 2017-02-07 17:21:27,420[nio-4401-exec-5]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 49]   - Web socket session opened
[STDOUT] 2017-02-07 17:21:27,420[nio-4401-exec-5]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 50]   - Endpoint: 228502892
[STDOUT] 2017-02-07 17:21:27,573[nio-4401-exec-3]  [ERROR] [o.e.c.a.v.w.FileWatcherService 198]  - Can't register dir /projects in file watch service
[STDOUT] java.io.IOException: User limit of inotify watches reached
[STDOUT]        at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264) ~[na:1.8.0_65]
[STDOUT]        at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260) ~[na:1.8.0_65]
[STDOUT]        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329) ~[na:1.8.0_65]
[STDOUT]        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
[STDOUT] 2017-02-07 17:21:27,804[nio-4401-exec-7]  [ERROR] [o.e.c.a.v.w.FileWatcherService 198]  - Can't register dir /projects/magento-dev in file watch service
[STDOUT] java.io.IOException: User limit of inotify watches reached
[STDOUT]        at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264) ~[na:1.8.0_65]
[STDOUT]        at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260) ~[na:1.8.0_65]
[STDOUT]        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329) ~[na:1.8.0_65]
[STDOUT]        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
[STDOUT] 2017-02-07 17:21:27,970[nio-4401-exec-4]  [ERROR] [o.e.c.a.v.w.FileWatcherService 198]  - Can't register dir /projects/magento-dev/app in file watch service
[STDOUT] java.io.IOException: User limit of inotify watches reached
[STDOUT]        at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264) ~[na:1.8.0_65]
[STDOUT]        at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260) ~[na:1.8.0_65]
[STDOUT]        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329) ~[na:1.8.0_65]
[STDOUT]        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
```
Probably we need to limit amount of inotify watchers per user/workspace and possible fallback to other methods of tracing changes in files, maybe polling.

**Codenvy version:**    5.2.2

**Comment by bmicklea** [comment]
@skryzhny is this reproducible in current versions?

**Comment by dkuleshov** [comment]
@bmicklea Hi, this issue was partially fixed a few sprints ago, so right now an error still rarely happens. However complete fix is not yet merged, there are several technical points to be discussed and resolved.
