### ISSUE TITLE
Unexpected errors after consuming a factory and creation of workspace

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1734]
**Reproduction Steps:** Sometimes after creation workspaces from stacks or consuming a factory we have exceptions like: 

```
2017-02-08 10:57:32,170[aceSharedPool-2]  [WARN ] [c.c.machine.RemoteDockerNode 101]    - The container '9026c92563bf0d6a447fefc4d4a08417bdd2f6befc163f1ac2eb7a5e2107c370' in the workspace 'workspacegziu8a0lih0agv
kw' won't be backed up. The reason is that the workspace wasn't restored from backup
2017-02-08 10:57:33,419[aceSharedPool-2]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 779]    - Error occurs while executing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-13.
pid ] && rm /tmp/docker-exec-13.pid' EXIT; echo $$>/tmp/docker-exec-13.pid; command -v pidof >/dev/null 2>&1 && {
    pidof sshd >/dev/null 2>&1 && echo 0 || echo 1
} || {
    ps -fC sshd >/dev/null 2>&1 && echo 0 || echo 1
}]: Error response from docker API, status: 404, message: Exec b98fb0f4a66de8046125e262ca520f7f6af68783440ac0032cf4baf095626779 not found

org.eclipse.che.api.core.ServerException: Error occurs while executing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-13.pid ] && rm /tmp/docker-exec-13.pid' EXIT; echo 
$$>/tmp/docker-exec-13.pid; command -v pidof >/dev/null 2>&1 && {
    pidof sshd >/dev/null 2>&1 && echo 0 || echo 1
} || {
    ps -fC sshd >/dev/null 2>&1 && echo 0 || echo 1
}]: Error response from docker API, status: 404, message: Exec b98fb0f4a66de8046125e262ca520f7f6af68783440ac0032cf4baf095626779 not found
        at org.eclipse.che.api.agent.server.launcher.AbstractAgentLauncher.launch(AbstractAgentLauncher.java:100) ~[che-core-api-agent-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695) ~[che-core-api-workspace-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048) ~[che-core-api-workspace-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:814) ~[che-core-api-workspace-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:265) ~[che-core-api-workspace-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) ~[che-core-api-workspace-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) ~[che-core-api-workspace-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102] 
```
This problem happens randomly

**Codenvy version:**   5.3.0

**OS and version:**    Ubuntu 14.0 TLS, Chrome browser

**Comment by garagatyi** [comment]
Looks like an issue with docker swarm. Probably it can miss exec as it does with images in some cases.

**Comment by garagatyi** [comment]
Probably eclipse/che#3971 fixes this problem

**Comment by garagatyi** [comment]
I created an issue for that problem in Swarm repo docker/swarm#2664
I'm going to workaround this problem with logging exec info + waiting some time and repeating exec start. 
This workaround could help either at runtime to bypass the problem or to find more info about it.

**Comment by garagatyi** [comment]
@TylerJewell it is swarm issue. What should we do with it?
