### ISSUE TITLE
Can't backup/restore workspaces because of old rsync version

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1814]
Got this errors:
```
2017-02-21 00:33:34,539[ceSharedPool-12]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspace*************' on node 'node7.codenvy.io' : Warning: Permanently added '[node7.codenv
rsync: on remote machine: --usermap=*:1000: unknown option
rsync error: syntax or usage error (code 1) at main.c(1435) [server=3.0.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
2017-02-21 00:33:34,540[ceSharedPool-12]  [ERROR] [DockerEnvironmentBackupManager 319]  - Synchronization process failed. Exit code 12
java.io.IOException: Synchronization process failed. Exit code 12
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:511) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreBackupInsideLock(DockerEnvironmentBackupManager.java:308) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreWorkspaceBackup(DockerEnvironmentBackupManager.java:194) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:94) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.agent.launcher.MachineInnerRsyncAgentLauncherImpl.launch(MachineInnerRsyncAgentLauncherImpl.java:68) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:816) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.3.0.jar:5.3.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) [che-core-commons-lang-5.3.0.jar:5.3.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```
This is because of old version of `rsync`, probably on old debian
Need to find way to work even on old debian or print message to user explaining why we can't start workspace.

Also please include more info in error message for second error, it probably related to previous one because of time difference is so small, but need to be sure.
So please include at least workspace ID in error message.

**Codenvy version:**    5.3.0

**OS and version:**    Centos 7.2

**Docker version:** 1.12.5

**Comment by garagatyi** [comment]
Error happens because rsync installed in container is older then expected by us. It doesn't support some options we use.

**Comment by skryzhny** [comment]
Can we detect that old version and run 'rsync' witht incompatible option and then change owner with `chown` command?

**Comment by levjason** [comment]
I am seeing the same error. Is there any workaround for this?

**Comment by garagatyi** [comment]
@skryzhny I suppose we can try that

**Comment by garagatyi** [comment]
@levjason What is your docker image where you have this error?

**Comment by levjason** [comment]
@garagatyi It is a Centos 7 image built here that contains a server for my company's products. I can start the image from the command line,  connect to it, and use the server. I suspect that the problem in Codenvy is not due to our server. I will try to create an image without the server and try to use that in Codenvy. Is there any other information you need?

**Comment by garagatyi** [comment]
Can you try `docker run -d <your_image> rsync --version`. And if it fails then 
`docker run -d <your_image> yum -y install rsync; rsync --version`

**Comment by levjason** [comment]
usajlev@usrscp29:~$ docker run -d -p6555:5555 1cd755993e27 rsync --version
f200582b90f11045655990aab7a265380b8349970ae45301077f0b15ca66df6d
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"rsync\": executable file not found in $PATH".
usajlev@usrscp29:~$

Next command:
usajlev@usrscp29:~$ docker run -d -p6555:5555 1cd755993e27 yum -y install rsync; rsync --version
6d35ec87e0d74b3d35bb98af60265d7ec75a141dd3c1285ea5c60080447dc745
rsync  version 3.1.1  protocol version 31
Copyright (C) 1996-2014 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

**Comment by garagatyi** [comment]
It is strange that you have this error. Rsync version is OK.

**Comment by levjason** [comment]
@garagatyi The first command says that rsync is not even installed, right? This same image worked fine last November in Che.

**Comment by garagatyi** [comment]
Can you try `docker run --rm <your_image> bash -c "yum -y install rsync; rsync --version"`

Che doesn't use rsync for projects syncing since it is one host only system.

**Comment by levjason** [comment]
usajlev@usrscp29:~$ docker run --rm  -p6555:5555 1cd755993e27 bash -c "yum -y install rsync; rsync --version"
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirror.datto.com
 * extras: mirror.us.leaseweb.net
 * updates: mirrors.lga7.us.voxel.net
Resolving Dependencies
--> Running transaction check
---> Package rsync.x86_64 0:3.0.9-17.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package         Arch             Version                  Repository      Size
================================================================================
Installing:
 rsync           x86_64           3.0.9-17.el7             base           360 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 360 k
Installed size: 732 k
Downloading packages:
warning: /var/cache/yum/x86_64/7/base/packages/rsync-3.0.9-17.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for rsync-3.0.9-17.el7.x86_64.rpm is not installed
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-3.1611.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : rsync-3.0.9-17.el7.x86_64                                    1/1
  Verifying  : rsync-3.0.9-17.el7.x86_64                                    1/1

Installed:
  rsync.x86_64 0:3.0.9-17.el7

Complete!
rsync  version 3.0.9  protocol version 30
Copyright (C) 1996-2011 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

**Comment by garagatyi** [comment]
OK, so you definitely faced the same problem with rsync version older then expected.

**Comment by levjason** [comment]
I couldn't find anything more current than rsync 3.0.9 for Centos. So I tried Codenvy's Ubuntu image. The build failed on rm commands in my dockerfile. I believe that this is a known problem. See https://github.com/docker/docker/issues/783

I finally got it to work with the latest fedora image on docker hub. 

Is the rsync 3.1.x requirement documented anywhere?

**Comment by garagatyi** [comment]
I think that we don't have it in docs.

**Comment by garagatyi** [comment]
We are investigating possibility to decrease minimal version of compatible rysnc.
If you can use image that has/installs rsync 3.1.0 or newer, please, use it for now.
