### ISSUE TITLE
ERROR 'java.lang.NullPointerException: null' when receiving factory

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1815]
Got this error:
```
2017-02-21 00:08:34,422[io-8080-exec-20]  [ERROR] [o.a.c.c.C.[.[.[.[default] 259]       - Servlet.service() for servlet [default] in context with path [/factory] threw exception
java.lang.NullPointerException: null
        at com.codenvy.onpremises.factory.filter.FactoryParamsFilter.doFilter(FactoryParamsFilter.java:80) ~[classes/:5.3.0]
        at com.codenvy.onpremises.factory.filter.RemoveIllegalCharactersFactoryURLFilter.doFilter(RemoveIllegalCharactersFactoryURLFilter.java:49) ~[classes/:5.3.0]
        at com.codenvy.onpremises.factory.filter.BrowserCheckerFilter.doFilter(BrowserCheckerFilter.java:87) ~[classes/:5.3.0]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) ~[guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.38]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) ~[catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.38]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.38]
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.38]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [catalina.jar:8.0.38]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100) [tomcat-coyote.jar:8.0.38]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687) [tomcat-coyote.jar:8.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-coyote.jar:8.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-coyote.jar:8.0.38]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.38]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```
It was thrown when processing this request `**.**.**.** - - [21/Feb/2017:00:08:34 +0000] "GET /factory/?name=spring-*****&amp;user=******* HTTP/1.1" 500 1712`

**Codenvy version:**    5.3.0

**Comment by mshaposhnik** [comment]
Will be fixed with moving factories into Che. Factory war is omitted in new realization.
