### ISSUE TITLE
Error when building simple android app project

### ISSUE THREAD

**Issue by Javac9** [codenvy/codenvy#1816]
I was hoping to get this Simple Androdi App quickly running but I got this error when trying to build with Maven:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-android 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ maven-android ---
[INFO] Deleting /projects/mobile-android-simple/target
[INFO] 
[INFO] --- android-maven-plugin:4.0.0-rc.2:generate-sources (default-generate-sources) @ maven-android ---
[INFO] Extracting libs
[INFO] Generating R file for org.hello:maven-android:apk:0.1.0
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: No Android SDK path could be found. You may configure it in the plugin configuration section in the pom file using ... or ... or on command-line using -Dandroid.sdk.path=... or by setting environment variable ANDROID_HOME
	at com.jayway.maven.plugins.android.AbstractAndroidMojo.getAndroidHomeOrThrow(AbstractAndroidMojo.java:1153)
	at com.jayway.maven.plugins.android.AbstractAndroidMojo.getAndroidSdk(AbstractAndroidMojo.java:1111)
```

**Comment by eivantsov** [comment]
@Javac9 what stack did you choose? It has to be Android stack

**Comment by Javac9** [comment]
@eivantsov You were right, I recreated my wksp and chose Android stack. But now these lines have these errors (squiggly red lines in the editor). However, I don't see any build errors.

`setContentView(R.layout.activity_main);`
`R cannot be resolved to a variable`

`getMenuInflater().inflate(com.codenvy.template.android.R.menu.main, menu);`
`com.codenvy.template.android.R cannot be resolved to a variable`


Full build output:

`[INFO] Building Codenvy Android Example 1.0-SNAPSHOT`
`[INFO] ------------------------------------------------------------------------`
`[INFO] `
`[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mobile-android-java-basic ---`
`[INFO] Deleting /projects/mobile-android-hello-world/target`
`[INFO] `
`[INFO] --- android-maven-plugin:4.0.0-rc.2:generate-sources (default-generate-sources) @ mobile-android-java-basic ---`
`[INFO] Extracting libs`
`[INFO] Generating R file for com.codenvy.examples:mobile-android-java-basic:apk:1.0-SNAPSHOT`
`[INFO] Adding R gen folder to compile classpath: /projects/mobile-android-hello-world/target/generated-sources/r`
`[INFO] Adding AIDL gen folder to compile classpath: /projects/mobile-android-hello-world/target/generated-sources/aidl`
`[INFO] `
`[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ mobile-android-java-basic ---`
`[INFO] Using 'UTF-8' encoding to copy filtered resources.`
`[INFO] skip non existing resourceDirectory /projects/mobile-android-hello-world/src/main/resources`
`[INFO] `
`[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ mobile-android-java-basic ---`
`[INFO] Changes detected - recompiling the module!`
`[INFO] Compiling 3 source files to /projects/mobile-android-hello-world/target/classes`
`[INFO] `
`[INFO] --- android-maven-plugin:4.0.0-rc.2:proguard (default-proguard) @ mobile-android-java-basic ---`
`[INFO] `
`[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ mobile-android-java-basic ---`
`[INFO] Using 'UTF-8' encoding to copy filtered resources.`
`[INFO] skip non existing resourceDirectory /projects/mobile-android-hello-world/src/test/resources`
`[INFO] `
`[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ mobile-android-java-basic ---`
`[INFO] No sources to compile`
`[INFO] `
`[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ mobile-android-java-basic ---`
`[INFO] No tests to run.`
`[INFO] `
`[INFO] --- android-maven-plugin:4.0.0-rc.2:emma (default-emma) @ mobile-android-java-basic ---`
`[INFO] `
`[INFO] --- android-maven-plugin:4.0.0-rc.2:dex (default-dex) @ mobile-android-java-basic ---`
`[INFO] Convert classes to Dex : /projects/mobile-android-hello-world/target/classes.dex`
`[INFO] `
`[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ mobile-android-java-basic ---`
`[INFO] Building jar: /projects/mobile-android-hello-world/target/mobile-android-java-basic.jar`
`[INFO] `
`[INFO] --- android-maven-plugin:4.0.0-rc.2:apk (default-apk) @ mobile-android-java-basic ---`
`[INFO] Generating debug apk.`
`[INFO] Adding native libraries : []`
`[INFO] `
`[INFO] --- android-maven-plugin:4.0.0-rc.2:internal-pre-integration-test (default-internal-pre-integration-test) @ mobile-android-java-basic ---`
`[INFO] No InstrumentationRunner found - skipping tests`
`[INFO] `
`[INFO] --- android-maven-plugin:4.0.0-rc.2:internal-integration-test (default-internal-integration-test) @ mobile-android-java-basic ---`
`[INFO] No InstrumentationRunner found - skipping tests`
`[INFO] `
`[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ mobile-android-java-basic ---`
`[INFO] Installing /projects/mobile-android-hello-world/target/mobile-android-java-basic.apk to /home/user/.m2/repository/com/codenvy/examples/mobile-android-java-basic/1.0-SNAPSHOT/mobile-android-java-basic-1.0-SNAPSHOT.apk`
`[INFO] Installing /projects/mobile-android-hello-world/pom.xml to /home/user/.m2/repository/com/codenvy/examples/mobile-android-java-basic/1.0-SNAPSHOT/mobile-android-java-basic-1.0-SNAPSHOT.pom`
`[INFO] Installing /projects/mobile-android-hello-world/target/mobile-android-java-basic.jar to /home/user/.m2/repository/com/codenvy/examples/mobile-android-java-basic/1.0-SNAPSHOT/mobile-android-java-basic-1.0-SNAPSHOT.jar`
`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD SUCCESS`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time: 19.504 s`
`[INFO] Finished at: 2017-02-22T18:34:14+00:00`
`[INFO] Final Memory: 26M/382M`
`[INFO] ------------------------------------------------------------------------`

**Comment by eivantsov** [comment]
R class is generated on the go, during the build. And it is not added to classpath. Here's a similar issue - https://github.com/codenvy/codenvy/issues/1397

**Comment by eivantsov** [comment]
Closing due to inactivity.
