### ISSUE TITLE
Rsync tries to connect on port 22

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1821]
Got errors in log - 'rsync' tries to connect workspace via port `22` while all our machines's `sshd` runs on ephemeral ports range `32768-65535`
It's blocker because of possible backup/restore corruption.
```
2017-02-21 10:13:00,592[pScheduler-2019]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspaceq10xenhtpbdv9jw1' on node 'node5.codenvy.io' : ssh: connect to host to port 22: Connection refused
ssh: connect to host to port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.2]
2017-02-21 10:13:00,593[pScheduler-2019]  [ERROR] [DockerEnvironmentBackupManager 356]  - Synchronization process failed. Exit code 255
java.io.IOException: Synchronization process failed. Exit code 255
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:511) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:347) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:228) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:127) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) [codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
2017-02-21 10:13:00,593[pScheduler-2019]  [ERROR] [m.b.WorkspaceFsBackupScheduler 112]  - Backup of workspace workspace****** filesystem terminated on node5.codenvy.io node. Synchronization process failed. Exit code 255
org.eclipse.che.api.core.ServerException: Backup of workspace workspaceq10xenhtpbdv9jw1 filesystem terminated on node5.codenvy.io node. Synchronization process failed. Exit code 255
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:359) ~[codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:228) ~[codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:127) ~[codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) ~[codenvy-machine-hosted-5.3.0.jar:5.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```

**Reproduction Steps:**
Don't know

**Codenvy version:**    5.3.0

**Comment by skryzhny** [comment]
Removed blocker because for more than week after update to 5.3.1 I didn't get that error.
Will monitor logs for such errors and report here if found any in the future.

**Comment by mmorhun** [comment]
Fixed by https://github.com/codenvy/codenvy/issues/1988
