### ISSUE TITLE
ERROR 'sync port is not exposed in ws-machine. Workspace projects syncing is not possible'

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1834]
Got bunch of these errors in log 
Need to include at least `workspaceID` in message
```
2017-02-24 09:01:16,460[aceSharedPool-5]  [ERROR] [c.c.machine.RemoteDockerNode 110]    - Sync port is not exposed in ws-machine. Workspace projects syncing is not possible
org.eclipse.che.api.core.ServerException: Sync port is not exposed in ws-machine. Workspace projects syncing is not possible
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.getSyncPort(DockerEnvironmentBackupManager.java:476) ~[codenvy-machine-hosted-5.3.1.jar:5.3.1]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspaceAndCleanup(DockerEnvironmentBackupManager.java:156) ~[codenvy-machine-hosted-5.3.1.jar:5.3.1]
        at com.codenvy.machine.RemoteDockerNode.unbindWorkspace(RemoteDockerNode.java:107) ~[codenvy-machine-hosted-5.3.1.jar:5.3.1]
        at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:268) [che-plugin-docker-machine-5.3.1.jar:5.3.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine$MachineCleaner.lambda$onEvent$0(CheEnvironmentEngine.java:1398) [che-core-api-workspace-5.3.1.jar:5.3.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.3.1.jar:5.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```

**Reproduction Steps:**
Don't know, probably recipe for workspace doesn't contain `tail -f /dev/null` or equivalent command.

**Codenvy version:**    5.3.1

**Comment by garagatyi** [comment]
Looks like container exited and we try to clean it up but don't expect for response docker returns.
Here is an example of docker inspect when container is running:
<details>

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b9d5d6c02d8e1e59f0c063ddbf034bd0f9dca888d0f942e47923c545be0e47df",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8000/tcp": null,
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/b9d5d6c02d8e",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "fd670db0deccde3411bc87b2e10e8a158ff38479cce06df3263b6419fed2608a",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:04",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "91085de04c55f6aa2d84bb00efd2e4831ea70a72f5407763f05c933f5c1a915e",
                    "EndpointID": "fd670db0deccde3411bc87b2e10e8a158ff38479cce06df3263b6419fed2608a",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:04"
                }
            }
        }
```
</details>

And here is an example of inspect of the same container when it is stopped:
<details>

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b9d5d6c02d8e1e59f0c063ddbf034bd0f9dca888d0f942e47923c545be0e47df",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "/var/run/docker/netns/b9d5d6c02d8e",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "91085de04c55f6aa2d84bb00efd2e4831ea70a72f5407763f05c933f5c1a915e",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
```
</details>

No `Ports` entry is present.

**Comment by garagatyi** [comment]
So we need to detect that container is not in running state and do not throw this weird error
