### ISSUE TITLE
Cannot run any workspace: Cannot run program "/opt/codenvy-data/conf/rsyncrestore.sh": error=13, Permission denied

### ISSUE THREAD

**Issue by MarcelRosenberger** [codenvy/codenvy#1877]
When trying to run **any** workspace an error occurs: 

_"**Start workspace error occurs**
Could not start workspace diagnostics. Reason: Start of environment 'diagnostics' failed. Error: Restoring of workspace workspacemtryj25eqhizbhvm filesystem terminated on 192.168.178.5 node. Cannot run program "/opt/codenvy-data/conf/rsyncrestore.sh": error=13, Permission denied"_

Setting `chmod +x /opt/codenvy-data/conf/rsyncrestore.sh` inside the container "codenvy service" didnt't help.

The docker run command is (under root):
`root@testsystem:~# docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /media/d7bd3742-...../codenvy:/data codenvy/cli:5.4.0 start`

The stack trace inside the "codenvy service" container is:

`2017-03-03 20:13:32,879[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 378]    - Workspace 'workspaceadcv7w6rux10te7j' removed by user 'admin'
2017-03-03 20:13:33,007[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 893]    - Workspace 'admin/diagnostics' with id 'workspacemtryj25eqhizbhvm' created by user 'admin'
2017-03-03 20:13:37,960[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.ssh' agent at workspace workspacemtryj25eqhizbhvm
2017-03-03 20:13:42,309[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'com.codenvy.rsync_in_machine' agent at workspace workspacemtryj25eqhizbhvm
2017-03-03 20:13:44,807[aceSharedPool-0]  [ERROR] [DockerEnvironmentBackupManager 319]  - Cannot run program "/opt/codenvy-data/conf/rsyncrestore.sh": error=13, Permission denied
java.io.IOException: Cannot run program "/opt/codenvy-data/conf/rsyncrestore.sh": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_111-internal]
        at org.eclipse.che.api.core.util.ProcessUtil.executeAndWait(ProcessUtil.java:105) ~[che-core-api-core-5.4.0.jar:5.4.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:506) [codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreBackupInsideLock(DockerEnvironmentBackupManager.java:308) [codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreWorkspaceBackup(DockerEnvironmentBackupManager.java:194) [codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:94) [codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at com.codenvy.machine.agent.launcher.MachineInnerRsyncAgentLauncherImpl.launch(MachineInnerRsyncAgentLauncherImpl.java:68) [codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:816) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) [che-core-commons-lang-5.4.0.jar:5.4.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.8.0_111-internal]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[na:1.8.0_111-internal]
        at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[na:1.8.0_111-internal]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_111-internal]
        ... 19 common frames omitted
2017-03-03 20:13:44,832[aceSharedPool-0]  [WARN ] [c.c.machine.RemoteDockerNode 101]    - The container '53f9bef815f4676fedd8108cf55f8c60da5e309b7149946319b6a082dfa6333b' in the workspace 'workspacemtryj25eqhizbhvm' won't be backed up. The reason is that the workspace wasn't restored from backup
2017-03-03 20:13:46,275[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Restoring of workspace workspacemtryj25eqhizbhvm filesystem terminated on 192.168.178.5 node. Cannot run program "/opt/codenvy-data/conf/rsyncrestore.sh": error=13, Permission denied
org.eclipse.che.api.core.ServerException: Restoring of workspace workspacemtryj25eqhizbhvm filesystem terminated on 192.168.178.5 node. Cannot run program "/opt/codenvy-data/conf/rsyncrestore.sh": error=13, Permission denied
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreBackupInsideLock(DockerEnvironmentBackupManager.java:322) ~[codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreWorkspaceBackup(DockerEnvironmentBackupManager.java:194) ~[codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:94) ~[codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at com.codenvy.machine.agent.launcher.MachineInnerRsyncAgentLauncherImpl.launch(MachineInnerRsyncAgentLauncherImpl.java:68) ~[codenvy-machine-hosted-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695) ~[che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048) ~[che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:816) ~[che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) ~[che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) ~[che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) ~[che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.4.0.jar:5.4.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.4.0.jar:5.4.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
`

**Reproduction Steps:**
 - Go to Codenvy Dashboard
 - Click on Diagnostics

**Codenvy version:**    
5.4.0

**OS and version:**    
Linux testsystem 4.9.0-0.bpo.1-amd64 #1 SMP Debian 4.9.2-2~bpo8+1 (2017-01-26) x86_64 GNU/Linux

**Docker version:**    
`Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: false`

**Codenvy cli.log output:**  
`HTTP/1.0 200 OK
Content-type: application/octet-stream
Date: Fri, 03 Mar 2017 20:01:09 GMT
Connection: close
Accept-Ranges: bytes
Last-Modified: Tue, 08 Nov 2016 19:28:30 GMT
Content-length: 6
[...]
INFO: (codenvy start):  Booted and reachable
INFO: (codenvy start):  Ver: 5.4.0
INFO: (codenvy start):  Use: http://192.168.178.5:80
INFO: (codenvy start):  API: http://192.168.178.5:80/swagger`

Any help is appeciated.

**Comment by TylerJewell** [comment]
@benoitf @garagatyi @eivantsov - this looks like an issue we have never seen before.  Maybe it could be due to the execution on debian?  Seems that the master doesn't even get workspace initiation initialized.

**Comment by garagatyi** [comment]
Tyler, I haven't seen this error before.
@MarcelRosenberger can you investigate permissions of this script inside of codenvy container. E.g. 
```
docker exec -it codenvy_codenvy_1 bash
ls -la /opt/codenvy-data/conf/rsyncrestore.sh
id
/opt/codenvy-data/conf/rsyncrestore.sh
```
I see that you were able to get inside of container to do chmod, so just for clarity these commands do: 
First one opens interactive shell inside of codenvy container.
Second, third and forth should be executed inside of this shell.
2nd shows permissions of script in container.
3rd shows who is current user in container and what his ids.
4th tries to execute this script and should fail, but needed to see what error will occur.

**Comment by MarcelRosenberger** [comment]
These are the results:

bash-4.3# ls -la /opt/codenvy-data/conf/rsyncrestore.sh
`-rwxr-xr-x    1 root     root          3202 Mar  3 18:20 /opt/codenvy-data/conf/rsyncrestore.sh`

bash-4.3# id
`uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)`

bash-4.3# /opt/codenvy-data/conf/rsyncrestore.sh
`bash: /opt/codenvy-data/conf/rsyncrestore.sh: Permission denied`

**Comment by garagatyi** [comment]
Thank you for the data. I suspect that your issue is related to additional security subsystem such as SELinux.
Can you execute on your host:
```
/usr/sbin/sestatus
```
and 
```
docker inspect codenvy_codenvy_1
```
@eivantsov has decent experience in figuring out the reason of issue with permissions.

**Comment by MarcelRosenberger** [comment]
Yes, sure!

`root@testsystem:~# /usr/sbin/sestatus`
`-bash: /usr/sbin/sestatus: No such file or directory`

and

`root@testsystem:~# docker inspect codenvy_codenvy_1`
_see attached_: [docker_inspect_codenvy_codenvy_1.txt](https://github.com/codenvy/codenvy/files/818952/docker_inspect_codenvy_codenvy_1.txt)

**Comment by eivantsov** [comment]
@MarcelRosenberger you are on Debian Jessie?

Yes, it does look like some security restrictions that make it impossible to execute mounted scripts.

I can see that your local data storage is in `/media` which I suspect is in its turn an NFC volume? It is just an assumption though. Can you stop Codenvy and re run with `-v ~/codenvy-data:/data` volume binding?

**Comment by eivantsov** [comment]
Probably, a good test to run is create an executable script in `/media/tmp` and execute:

`docker run -v /media/tmp:/data alpine:3.4 sh -c "/media/tmp/script.sh" `

**Comment by MarcelRosenberger** [comment]
@eivantsov Perfect suggestions!

1) Running Codenvy using `-v ~/codenvy-data:/data` works without throwing "Permission denied".
2) Running `docker run -v /media/tmp:/data alpine:3.4 sh -c "/data/tmp/script.sh"` throws "Permission denied"

I am on Debian Jessie. `/media` is not an NFS volume. 

**Root cause**
`# cat /etc/mtab`
`/dev/sda1 /media/d7bd3742-... xfs rw,noexec,relatime,attr2,inode64,usrquota,grpquota 0 0`

**Solution**
Removing `noexec` from `/etc/fstab` and re-mounting `/media/d7bd3742-....` finally solved the error. Workspaces are starting.

@TylerJewell @eivantsov @garagatyi Thanks for your help!

**Comment by TylerJewell** [comment]
@eivantsov @MarcelRosenberger - before I close this issue, is there any thoughts about how we could package this test into the CLI, so that we can detect this situation and abort before Che or Codenvy is started?

I would need an environment where this issue exists, and the test to apply. For example, if a user passed in `/tmp:/data`, then would run `docker run -v /tmp/tmp:/test alpine:3.4 sh -c "/test/tmp/script.sh"`.  We would look for some non-standard error code and then return that we have uncovered some sort of permissions issue and that you must check for noexec, selinux, or other parameters.

**Comment by MarcelRosenberger** [comment]
Surprisingly, I could run Che and start workspaces without any issues from the **same** volume, which was mounted with `noexec`. So it seems to be exclusive to Codenvy.

**Comment by TylerJewell** [comment]
Well that could be an interesting clue.  The key distinction here is that workspaces for Che are started directly with docker engine.  However codenvy uses swarm to start workspaces and they are created in a docker network. 

So perhaps @garagtyi - there is some sort of extra test that codenvy needs to perform against file systems to test for this extra condition for swarm?

**Comment by eivantsov** [comment]
Che does not use rsync. Pure volume mounts

**Comment by garagatyi** [comment]
Yes, @eivantsov is absolutely correct.
In Codenvy data volume contains rsync scripts. Since it disallow executable permissions we can't start it.
In Che we don't use these scripts, so everything is working.

**Comment by TylerJewell** [comment]
@garagatyi - what test do you recommend that we perform in preflight checks to verify that rsync scripts would work properly?

**Comment by garagatyi** [comment]
Add executable script script.sh that prints something like "Hello, CLI" into image and run:
`docker run -v <expected_host_path>:/data ./script.sh`
Then check output.

**Comment by eivantsov** [comment]
@garagatyi I think you mean `/data/script.sh`

Yeah, smth like that - it's what I asked @MarcelRosenberger to do in fact.

**Comment by garagatyi** [comment]
Yes, I updated my comment

**Comment by TylerJewell** [comment]
Ok, so effectively the test is to run a simple script in the folder mounted to `:/data`.  Now, in reality since the CLI is already running in a container, then we need to:
1. Copy a file from inside the image to /data folder.
2. Execute that file
3. Test the results
4. Remove the file

**Comment by eivantsov** [comment]
@TylerJewell yes, something like that. I'd remove the file after executing it. `/data/script.sh && rm /data/script.sh`

**Comment by TylerJewell** [comment]
Here is a PR for this additional check.  https://github.com/eclipse/che/pull/4326

**Comment by eivantsov** [comment]
@MarcelRosenberger are you ok with closing this issue?

**Comment by MarcelRosenberger** [comment]
@eivantsov Yes. Thanks, once again!
