### ISSUE TITLE
Error when starting codenvy 'An attempt to clean up resources due to user creation failure'

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1887]
Got this error in logs when starting codenvy:
<details>

```
2017-03-06 14:57:35,045[ost-startStop-1]  [ERROR] [o.e.c.a.u.server.UserManager 109]    - An attempt to clean up resources due to user creation failure was unsuccessful.Now the system may be in inconsistent state. User with id 'adminstg' 
must not exist
org.eclipse.che.api.core.ServerException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
Error Code: 0
Call: INSERT INTO usr (id, email, name, password) VALUES (?, ?, ?, ?)
        bind => [4 parameters bound]
Query: InsertObjectQuery(UserImpl{id='************', email='******@*********', name='*********', password='*************************************:44f50d691feadd40:10000', aliases=[]})
        at com.codenvy.api.workspace.server.spi.jpa.JpaStackPermissionsDao.doGetByUser(JpaStackPermissionsDao.java:136) ~[codenvy-hosted-api-workspace-5.4.1.jar:5.4.1]
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:62) ~[guice-persist-4.1.0.jar:na]
        at com.codenvy.api.workspace.server.spi.jpa.JpaStackPermissionsDao.getByUser(JpaStackPermissionsDao.java:71) ~[codenvy-hosted-api-workspace-5.4.1.jar:5.4.1]
        at com.codenvy.api.permission.server.jpa.listener.RemovePermissionsOnLastUserRemovedEventSubscriber.onCascadeEvent(RemovePermissionsOnLastUserRemovedEventSubscriber.java:62) ~[codenvy-hosted-api-permission-5.4.1.jar:5.4.1]
        at com.codenvy.api.permission.server.jpa.listener.RemovePermissionsOnLastUserRemovedEventSubscriber.onCascadeEvent(RemovePermissionsOnLastUserRemovedEventSubscriber.java:41) ~[codenvy-hosted-api-permission-5.4.1.jar:5.4.1]
        at org.eclipse.che.core.db.cascade.CascadeEventSubscriber.onEvent(CascadeEventSubscriber.java:28) ~[che-core-db-5.4.1.jar:5.4.1]
        at org.eclipse.che.core.db.cascade.CascadeEventSubscriber.onEvent(CascadeEventSubscriber.java:23) ~[che-core-db-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:106) ~[che-core-api-core-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.user.server.jpa.JpaUserDao.doRemove(JpaUserDao.java:246) ~[che-core-api-user-5.4.1.jar:5.4.1]
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:62) ~[guice-persist-4.1.0.jar:na]
        at org.eclipse.che.api.user.server.jpa.JpaUserDao.remove(JpaUserDao.java:113) ~[che-core-api-user-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.user.server.UserManager.create(UserManager.java:105) ~[che-core-api-user-5.4.1.jar:5.4.1]
        at com.codenvy.organization.api.personal.SaasUserManager.create(SaasUserManager.java:61) ~[saas-personal-organization-5.4.1.jar:5.4.1]
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:70) ~[guice-persist-4.1.0.jar:na]
        at com.codenvy.api.user.server.AdminUserCreator.create(AdminUserCreator.java:96) [codenvy-hosted-api-admin-5.4.1.jar:5.4.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
        at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44) [che-core-commons-inject-5.4.1.jar:5.4.1]
        at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119) [guice-4.1.0.jar:na]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121) [guice-4.1.0.jar:na]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) [guice-4.1.0.jar:na]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) [guice-4.1.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [guice-4.1.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) [guice-4.1.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-4.1.0.jar:na]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) [guice-4.1.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [guice-4.1.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) [guice-4.1.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) [guice-4.1.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) [guice-4.1.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) [guice-4.1.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) [guice-4.1.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) [guice-4.1.0.jar:na]
        at com.google.inject.Guice.createInjector(Guice.java:99) [guice-4.1.0.jar:na]
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140) [everrest-integration-guice-1.13.3.jar:na]
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) [guice-servlet-4.1.0.jar:na]
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85) [everrest-integration-guice-1.13.3.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314) [catalina.jar:8.0.38]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.38]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940) [catalina.jar:8.0.38]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816) [catalina.jar:8.0.38]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
```

</details>

**Reproduction Steps:**
Probably regular user with such email already exist in DB.

**Codenvy version:**     5.4.1

**Comment by evoevodin** [comment]
The database is in consistent state, the issue is not actual any more as _the synthetic transaction_ was [replaced](https://github.com/eclipse/che/pull/4478/files) by a regular one.
