### ISSUE TITLE
Using google component registry for workspaces

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1893]
**Reproduction Steps:**
Once gcr can be configured as per other defect.
I don't see a way to prefix or control the name of the workspace snapshot.
When using the google component registry all docker push there have to be tagged with
```
<googleprojectname>/
```
 i.e. the URL needs to be
```
us.gcr.io/<googleprojectname>/<name>:<tag>
```
**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
Labeling as enhancement. We have a way to use username when pushing to DockerHub for example. But gcr has it's own format, and Che isn't certified yet to work with it.

**Comment by richtera** [comment]
I can pull the item using plain docker.
```
andy@ubuntu:~/selfstudy-jenkins/codenvy$ docker login us.gcr.io
Username (oauth2accesstoken): 
Password: 
Login Succeeded
andy@ubuntu:~/selfstudy-jenkins/codenvy$ docker pull us.gcr.io/<project>/codenvy-node-git-crypt
Using default tag: latest
latest: Pulling from <project>/codenvy-node-git-crypt
Digest: sha256:*****
Status: Downloaded newer image for us.gcr.io/<project>/codenvy-node-git-crypt:latest
andy@ubuntu:~/selfstudy-jenkins/codenvy$ 
```

**Comment by TylerJewell** [comment]
Unfortunately that isn't a great test for compatibility.  We go right to the docker API, and we have found that there is little validation in the API itself.  So the docker client you tested on can have a lot of validation or transformations built in.  And every so often our client to the API needs to adapt to have similar behavior.

**Comment by richtera** [comment]
Ok. Not sure how to help. I tried it one more time and the error is a bit more explicit:
```
[DOCKER] Pulling repository us.gcr.io/<project>/codenvy-node-git-crypt 
[DOCKER] [ERROR] Error: Status 403 trying to pull repository <project>/codenvy-node-git-crypt: "Unable to access the repository: <project>/codenvy-node-git-crypt; please verify that it exists and you have permission to access it (no valid credential was supplied)."
[ERROR] Docker image build failed. Image id not found in build output.
```
No valid credentials was supplied seems to me that it did not recognize the CODENVY_DOCKER_AUTH_... setup in the env file.

**Comment by richtera** [comment]
I am now trying canister.io and I am seeing similar problems.
![image](https://cloud.githubusercontent.com/assets/708186/23725752/cb3d32c2-041f-11e7-9ffd-6fd44cfa9ef4.png)
It's giving me some kind of weird error when I try to add the registry.

**Comment by richtera** [comment]
trying using the variables.

**Comment by richtera** [comment]
Added the canister.io registry and having the same problem.
```
017-03-09 04:42:16,535[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Docker image build failed. Image id not found in build output.
org.eclipse.che.api.core.ServerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1004) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:810) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.4.1.jar:5.4.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
Caused by: org.eclipse.che.api.core.ServerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:335) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:782) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:946) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        ... 11 common frames omitted
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Docker image build failed. Image id not found in build output.
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:196) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.prepareImage(MachineProviderImpl.java:379) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:276) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        ... 13 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:829) ~[che-plugin-docker-client-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:752) ~[che-plugin-docker-client-5.4.1.jar:5.4.1]
        at com.codenvy.swarm.client.SwarmDockerConnector.buildImage(SwarmDockerConnector.java:88) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:179) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        ... 15 common frames omitted
```

**Comment by richtera** [comment]
I found some errors in the docker system logs pulling from the registry.
But pulling manually and therefore making the docker tag available on the machine still doesn't work. I am not sure what to try next.

**Comment by eivantsov** [comment]
I'll try to register with canister.io and give it a shot myself. The errors you see are due to inability to pull the image.

**Comment by richtera** [comment]
I am going to change my machine type from CoreOS to ubuntu just to see if I am hitting something completely outside of anything I could think of.

**Comment by eivantsov** [comment]
@richtera I do not think changing OS helps here.

Weird, I cannot register with canister.io to test it myself. Waiting for their response.

**Comment by richtera** [comment]
Ok I did find something interesting. The oath2accesstoken is not a useful gcr login. There is a more permanent version that uses the json file. This one gets closer to "working". Now I get a more specific error:
```
[DOCKER] Step 1 : FROM us.gcr.io/master-mote-735/codenvy-node-git-crypt
[DOCKER] [ERROR] Get https://us.gcr.io/v2/master-mote-735/codenvy-node-git-crypt/manifests/latest: unknown: Unable to parse json key.
[ERROR] Docker image build failed. Image id not found in build output.
```
So I got it working by changing the login to a json file!!!
Thanks
Andy

**Comment by richtera** [comment]
Success! Workspace is all up and running (the previous post was just a test workspace thing.) Launched to be doubly sure.
```
user@58eeb706a4cf:/projects$ git crypt
Usage: git-crypt COMMAND [ARGS ...]

Common commands:
  init                 generate a key and prepare repo to use git-crypt
  status               display which files are encrypted
  lock                 de-configure git-crypt and re-encrypt files in work tree
...
```
You can close this defect. There might be something else going on with canister.io. Whatever is happening actually locked out my canister account, but if gcr works I am ok.

**Comment by TylerJewell** [comment]
My god ... I love the persistence and critical thinking, @richtera - thanks for sticking with it.

**Comment by eivantsov** [comment]
@richtera can you elaborate on how changed login to json file and configured Codenvy to be using it?

**Comment by richtera** [comment]
I copied in from the console after
```
onsole.log(JSON.stringify(require('./service account.json'))
```
This puts the content on a single line for the environment file. Ideally you want to allow pasting it into the password field.

**Comment by richtera** [comment]
Will a google component registry be in the future? I am trying to figure out whether I can plan to use a hosted version of codenvy in the future and when.

**Comment by eivantsov** [comment]
@richtera I am a little bit confused - you got it up and running, didn't you? Adding a registry in .env file isn't a workaround but a legitimate way of adding a registry.
