### ISSUE TITLE
Unable to create custom dockers internally

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1896]
**Reproduction Steps:**
Configuring a Stack

I cannot get "type": "dockerfile" to work as in:

![image](https://cloud.githubusercontent.com/assets/708186/23664509/c3f2dce4-0323-11e7-8378-84a49e21c846.png)

I just removes my "content" tag from the stack configuration content when I click save.
Is this outdated documentation?

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
@richtera disregard source. You need to provide recipe in workspaceconfig: https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L171-L173

In your case it will be:

```
          "recipe":{
            "content":"FROM codenvy/artik\nRUN echo hello world\nENV MYCUSTOM=VALUE",
            "contentType":"text/x-dockerfile",
            "type":"dockerfile"
          }
```

Yes, docs are outdated. @JamesDrummond please take a look.

**Comment by richtera** [comment]
No matter what I try. Docker registries or local FROM builds everything results in the same error:
```
2017-03-09 04:53:12,549[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Docker image build failed. Image id not found in build output.
org.eclipse.che.api.core.ServerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1004) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:810) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.4.1.jar:5.4.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
Caused by: org.eclipse.che.api.core.ServerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:335) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:782) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:946) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        ... 11 common frames omitted
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Docker image build failed. Image id not found in build output.
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:196) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.prepareImage(MachineProviderImpl.java:379) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:276) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        ... 13 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:829) ~[che-plugin-docker-client-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:752) ~[che-plugin-docker-client-5.4.1.jar:5.4.1]
        at com.codenvy.swarm.client.SwarmDockerConnector.buildImage(SwarmDockerConnector.java:88) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:179) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        ... 15 common frames omitted
```
Is there any way to see what docker build is actually returning from the API call?

**Comment by richtera** [comment]
There are some docker errors in the os logs.... researching.

**Comment by TylerJewell** [comment]
closing due to inactivity
