### ISSUE TITLE
Error 'java.lang.InterruptedException: null'

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1968]
Got several errors
```
2017-03-21 14:07:19,094[aceSharedPool-8]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 795]    - Workspace '*******' with id 'workspace*******' is being stopped by user '**************'
2017-03-21 14:07:19,096[ceSharedPool-10]  [ERROR] [DockerEnvironmentBackupManager 315]  - null
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_111-internal]
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:412) ~[na:1.8.0_111-internal]
	at org.eclipse.che.api.core.util.ProcessUtil.executeAndWait(ProcessUtil.java:117) ~[che-core-api-core-5.5.0.jar:5.5.0]
	at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:506) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
	at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreBackupInsideLock(DockerEnvironmentBackupManager.java:308) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
	at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreWorkspaceBackup(DockerEnvironmentBackupManager.java:194) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
	at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:94) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
	at com.codenvy.machine.agent.launcher.MachineInnerRsyncAgentLauncherImpl.launch(MachineInnerRsyncAgentLauncherImpl.java:68) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695) [che-core-api-workspace-5.5.0.jar:5.5.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048) [che-core-api-workspace-5.5.0.jar:5.5.0]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:816) [che-core-api-workspace-5.5.0.jar:5.5.0]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) [che-core-api-workspace-5.5.0.jar:5.5.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) [che-core-api-workspace-5.5.0.jar:5.5.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) [che-core-api-workspace-5.5.0.jar:5.5.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.5.0.jar:5.5.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.5.0.jar:5.5.0]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) [che-core-commons-lang-5.5.0.jar:5.5.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```
All observed errors occurred just few milliseconds after `Workspace '*******' with id 'workspace*******' is being stopped by user '**************'`

**Reproduction Steps:**
Don't know

**Codenvy version:** 5.5.1

**Comment by mmorhun** [comment]
This was fixed in 5.7.0
