### ISSUE TITLE
If docker recipe is empty throw WARNING instead of ERROR

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1970]
Got that error, I think it better convert from ERROR to WARNING and don't print stacktrace:
```
2017-03-20 16:10:03,180[io-8080-exec-15]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2017-03-20 16:10:02
java.lang.NullPointerException: Recipe content type should not be null
        at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_111-internal]
        at org.eclipse.che.plugin.docker.compose.yaml.ComposeEnvironmentParser.parse(ComposeEnvironmentParser.java:87) ~[che-plugin-docker-compose-5.5.0.jar:5.5.0]
        at org.eclipse.che.plugin.docker.compose.yaml.ComposeEnvironmentParser.parse(ComposeEnvironmentParser.java:71) ~[che-plugin-docker-compose-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.environment.server.EnvironmentParser.parse(EnvironmentParser.java:90) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.environment.server.CheEnvironmentValidator.validate(CheEnvironmentValidator.java:109) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.DefaultWorkspaceValidator.validateConfig(DefaultWorkspaceValidator.java:72) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.DefaultWorkspaceValidator.validateWorkspace(DefaultWorkspaceValidator.java:50) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.WorkspaceService.update(WorkspaceService.java:271) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at sun.reflect.GeneratedMethodAccessor462.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120) [everrest-core-1.13.3.jar:na]
        at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61) [everrest-core-1.13.3.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436) [catalina.jar:8.0.38]
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177) [catalina.jar:8.0.38]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.codenvy.api.license.filter.SystemLicenseLoginFilter.doFilter(SystemLicenseLoginFilter.java:118) [codenvy-hosted-api-system-license-filters-5.5.0.jar:5.5.0]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.codenvy.auth.sso.client.DefaultTokenHandler.handleValidToken(DefaultTokenHandler.java:65) [codenvy-hosted-sso-client-5.5.0.jar:5.5.0]
        at com.codenvy.api.permission.server.PermissionTokenHandler.handleValidToken(PermissionTokenHandler.java:64) [codenvy-hosted-authorization-5.5.0.jar:5.5.0]
        at com.codenvy.auth.sso.client.LoginFilter.doFilter(LoginFilter.java:120) [codenvy-hosted-sso-client-5.5.0.jar:5.5.0]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.38]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.38]
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.38]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [catalina.jar:8.0.38]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100) [tomcat-coyote.jar:8.0.38]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687) [tomcat-coyote.jar:8.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-coyote.jar:8.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-coyote.jar:8.0.38]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.38]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```

**Reproduction Steps:**
Don't know, probably supply empty recipe?

**Codenvy version:**  5.5.1

**Comment by eivantsov** [comment]
@garagatyi @mmorhun do you think it is a reasonable request? I do understand it litters logs, but on the other hand an empty recipe is an error both in terms of Docker and Che.

**Comment by garagatyi** [comment]
In this particular case the error should be shown to user, but should not be logged. I suppose it is requested behavior

**Comment by eivantsov** [comment]
A user cannot create and start a workspace with an empty recipe, UD validates it now. I am pretty sure @skryzhny does not want this error to be logged as error.
