### ISSUE TITLE
Tkinter and Codenvy

### ISSUE THREAD

**Issue by vteyssier** [codenvy/codenvy#1976]
Hi,

I'm new to Codenvy and having issue using python with Tk.

First when trying to import tkinter : 

Python 3.5.1 (default, Mar 21 2017, 15:40:09)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tkinter import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/tkinter/__init__.py", line 35, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named '_tkinter'
>>>

Then, also having issues when trying to import python lib : 
Python 3.5.1 (default, Mar 21 2017, 15:40:09)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import missingno as msno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/missingno/__init__.py", line 1, in <module>
    from .missingno import matrix
  File "/usr/local/lib/python3.5/site-packages/missingno/missingno.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python3.5/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.5/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.5/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/lib/python3.5/tkinter/__init__.py", line 35, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
Import

I installed tk-dev and python-tk.
Unfortunately, this did not solve the issue.

Can you please help ?

Many thanks

Vincent

**Reproduction Steps:**

**Codenvy version:**    5.5.0

**Comment by vteyssier** [comment]
Is there any way to use python3.5 with tk in Codenvy ?
Thx

**Comment by eivantsov** [comment]
@vteyssier i think your question should sound like "Is there any way to use Python 3.5 with tk on Ubuntu 16.04 which our Python stack is based on". Codenvy itself does not provide anything specific to Python.

Also, there's no x-server in a python stack, which means you won't be able to develop and preview GUI programs.

I will have some time this weekend to give it a shot myself.

**Comment by eivantsov** [comment]
@vteyssier you need to use `eclipse/x11_vnc` image, install python there and create a command (any command like echo hello world) with the following preview URL http://${server.port.6080}. Once in a noVNC window, right click gray area, open a terminal, navigate to /projects/yourProject and run python commands from there.

**Comment by eivantsov** [comment]
Closed due to inactivity.
