### ISSUE TITLE
rsyncrestore.sh script sometime fails

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1988]
Got exceptions in logs like:
```
2017-03-26 08:49:01,730[pScheduler-4347]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspace*************' on node 'node17.codenvy.io' : ssh: Could not resolve hostname error:: 
ssh: Could not resolve hostname error:: Name does not resolve
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.2]
2017-03-26 08:49:01,731[pScheduler-4347]  [ERROR] [DockerEnvironmentBackupManager 356]  - Synchronization process failed. Exit code 255
java.io.IOException: Synchronization process failed. Exit code 255
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:511) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:347) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:228) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:127) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
2017-03-26 08:49:01,732[pScheduler-4347]  [ERROR] [m.b.WorkspaceFsBackupScheduler 112]  - Backup of workspace workspace************** filesystem terminated on node17.codenvy.io node. Synchronization process failed. Exit code 255
org.eclipse.che.api.core.ServerException: Backup of workspace workspace************* filesystem terminated on node17.codenvy.io node. Synchronization process failed. Exit code 255
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:359) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:228) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:127) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```
When debugging script found out that usual error message for non-existent hostname is:
```
# ./rsyncrestore.sh 1 2 non-existent.host.name.zzz 40472 5 6 user
ssh: Could not resolve hostname non-existent.host.name.zzz: Name does not resolve
```
So value `error:` is supplied to script instead of hostname

**Reproduction Steps:**
Don't know

**Codenvy version:**    5.5.1-SaaS

Setting blocker because it is potentially affecting integrity of projects.
If that issue couldn't lead to project's loss feel free to lower issue priority.

**Comment by garagatyi** [comment]
I haven't found the reason of the problem. @skryzhny  and I decided to add logs in rsync scripts on prod to figure out more information. 
Luckily we will got enough information soon to continue work on this issue.

**Comment by mmorhun** [comment]
Done
