### ISSUE TITLE
For scheduled backups if there errors related to changed/vanished files change loglevel to WARN and don't print stacktrace

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#2018]
We doing scheduled backups of workspace and it expected that in time of backup(rsync) some files are changed or even deleted.
https://lxadm.com/Rsync_exit_codes
So if we detected exit code 24 and probably 23 for **scheduled backups** then change loglevel from ERROR to WARN and don't print stacktrace.
Example of ERROR
<details>

```
2017-03-30 09:32:14,132[Scheduler-16966]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspace***' on node 'node13.codenvy.io' : Warning: Permanently added '[node13.code
Authenticated to node13.codenvy.io ([172.30.12.113]:39118).
Transferred: sent 2336, received 2244 bytes, in 0.0 seconds
Bytes per second: sent 79648.0, received 76511.1
Warning: Permanently added '[node13.codenvy.io]:39118,[172.30.12.113]:39118' (ECDSA) to the list of known hosts.
Authenticated to node13.codenvy.io ([172.30.12.113]:39118).
file has vanished: "/projects/arch/root.x86_64/var/lib/pacman/db.lck"
Transferred: sent 23508, received 82885960 bytes, in 12.1 seconds
Bytes per second: sent 1941.9, received 6846984.6
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1650) [generator=3.1.2]
2017-03-30 09:32:14,132[Scheduler-16966]  [ERROR] [DockerEnvironmentBackupManager 356]  - Synchronization process failed. Exit code 24
java.io.IOException: Synchronization process failed. Exit code 24
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:511) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:347) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:228) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:127) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) [codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
2017-03-30 09:32:14,133[Scheduler-16966]  [ERROR] [m.b.WorkspaceFsBackupScheduler 112]  - Backup of workspace workspace*** filesystem terminated on node13.codenvy.io node. Synchronization process failed. Exit code 24
org.eclipse.che.api.core.ServerException: Backup of workspace workspace*** filesystem terminated on node13.codenvy.io node. Synchronization process failed. Exit code 24
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:359) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupInsideLock(DockerEnvironmentBackupManager.java:228) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspace(DockerEnvironmentBackupManager.java:127) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:106) ~[codenvy-machine-hosted-5.5.0.jar:5.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```
</details>

In some case there may be thousands of lines in log listing vanished files.

**Codenvy version:** 5.5.1-SaaS

**Comment by skryzhny** [comment]
From nightly server with code 23
<details>

```
2017-03-30 08:26:42,704[aceSharedPool-6]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspacepd2hwzyq5hvx7ld0' on node 'node2.nightly.codenvy-stg.com' : Warning: Permanently added '
Warning: Permanently added '[node2.nightly.codenvy-stg.com]:34278,[172.30.22.102]:34278' (ECDSA) to the list of known hosts.
rsync: stat "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/.git/objects/pack/.pack-6918087004a6685ada44a5ad4fcb0f501aaebd57.pack.feIHfn" failed: No such file or directory (2)
rsync: rename "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/.git/objects/pack/.pack-6918087004a6685ada44a5ad4fcb0f501aaebd57.pack.feIHfn" -> "che/.git/objects/pack/pack-6918087004a6685ada44a5ad4fcb0f501aaebd57.pack": No suc
rsync: mkstemp "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/.git/refs/heads/.4.7.x.XXXXXX" failed: No such file or directory (2)

...
THERE WAS LOTS OF SIMILAR LINES
....

sync: mkstemp "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/dashboard/src/app/workspaces/create-workspace/select-stack/.workspace-select-stack.directive.js.XXXXXX" failed: No such file or directory (2)
rsync: mkstemp "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/dashboard/src/app/workspaces/create-workspace/select-stack/.workspace-select-stack.html.XXXXXX" failed: No such file or directory (2)
rsync: recv_generator: mkdir "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/plugins" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/samples" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/wsagent" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/opt/codenvy-data/fs/b0/1d/65/workspacepd2hwzyq5hvx7ld0/che/wsmaster" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1650) [generator=3.1.2]
2017-03-30 08:26:42,706[aceSharedPool-6]  [ERROR] [DockerEnvironmentBackupManager 356]  - Synchronization process failed. Exit code 23
java.io.IOException: Synchronization process failed. Exit code 23
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeCommand(DockerEnvironmentBackupManager.java:511) [codenvy-machine-hosted-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.executeBackupScript(DockerEnvironmentBackupManager.java:347) [codenvy-machine-hosted-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupAndCleanupInsideLock(DockerEnvironmentBackupManager.java:260) [codenvy-machine-hosted-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.backupWorkspaceAndCleanup(DockerEnvironmentBackupManager.java:159) [codenvy-machine-hosted-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at com.codenvy.machine.RemoteDockerNode.unbindWorkspace(RemoteDockerNode.java:107) [codenvy-machine-hosted-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:268) [che-plugin-docker-machine-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1174) [che-core-api-workspace-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1151) [che-core-api-workspace-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:331) [che-core-api-workspace-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stopEnvironmentAndPublishEvents(WorkspaceRuntimes.java:803) [che-core-api-workspace-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:371) [che-core-api-workspace-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$3(WorkspaceManager.java:825) [che-core-api-workspace-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```
</details>
