### ISSUE TITLE
Python Project Requirements only load first time, never thereafter

### ISSUE THREAD

**Issue by JN214** [codenvy/codenvy#2088]
Please excuse any misstep on my first posting here.

I use the ready-made Python project creation in a new workspace. At first, I can "pip install" any package in my custom-made virtualenv folder. As usual, I freeze the packages into a requirements.txt file. Whenever I log back into my workspace/project a second time or more, I can never install any more packages through the "pip install" command line. I have done this multiple times so this is a repeatable and duplicable issue. Why can't I install package beyond the first time?

A typical error is of the sort:
user@8ad41ea3d5b2:/projects$ ls
HW4
user@8ad41ea3d5b2:/projects$ cd HW4
user@8ad41ea3d5b2:/projects/HW4$ ls
HW4env  main.py
user@8ad41ea3d5b2:/projects/HW4$ cd HW4env
user@8ad41ea3d5b2:/projects/HW4/HW4env$ ls
bin  include  lib  pip-selfcheck.json  requirements.txt
user@8ad41ea3d5b2:/projects/HW4/HW4env$ source bin/activate
(HW4env) user@8ad41ea3d5b2:/projects/HW4/HW4env$ pip install numpy
Collecting numpy
  Using cached numpy-1.12.1-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: numpy
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/site-packages/numpy-1.12.1.dist-info'
(HW4env) user@8ad41ea3d5b2:/projects/HW4/HW4env$

**Comment by eivantsov** [comment]
@JN214 `sudo` should probably fix it.

**Comment by eivantsov** [comment]
@JN214 were you able to install packages? Just tried it with sudo and it worked like a charm.

**Comment by eivantsov** [comment]
@JN214 any update please?

**Comment by eivantsov** [comment]
Closed due to inactivity.
