### ISSUE TITLE
Not enough information for investigate error 'The Che server is unable to ping your workspace.'

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#2129]
Got several errors like
<details>

```
2017-04-24 00:25:43,795[ceSharedPool-15]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:128) ~[wsagent-5.8.1.jar:5.8.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695) ~[che-core-api-workspace-5.8.1.jar:5.8.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048) ~[che-core-api-workspace-5.8.1.jar:5.8.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:819) ~[che-core-api-workspace-5.8.1.jar:5.8.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:268) ~[che-core-api-workspace-5.8.1.jar:5.8.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:712) ~[che-core-api-workspace-5.8.1.jar:5.8.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) ~[che-core-api-workspace-5.8.1.jar:5.8.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:977) [che-core-api-workspace-5.8.1.jar:5.8.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:941) [che-core-api-workspace-5.8.1.jar:5.8.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.8.1.jar:5.8.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```
</details>
It's very hard to guess workspace caused that error.
Please include at least WorkspaceId in error message.
Also if possible add workspace namespace/name, node, machineId, etc.

**Reproduction Steps:**
Don't know. probably cut network connection to node.

**Codenvy version:**    5.8.1-SaaS

**Comment by mmorhun** [comment]
Done
