### ISSUE TITLE
Regression: workaround for retrying pull image doesn't work after update to docker 17.04

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#2144]
Got bunch of errors like:
<details>

```
2017-04-27 09:22:34,873[ceSharedPool-14]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Error response from docker API, status: 500, message: Error response from daemon: repository eclipse-che/workspacejvuc8i8is9zcdsjr_machine9doqmbeyb2
mc16xm_factorycheck_dev-machine not found: does not exist or no pull access

org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error response from daemon: repository eclipse-che/workspacejvuc8i8is9zcdsjr_machine9doqmbeyb2mc16xm_factorycheck_dev-machine not found: does 
not exist or no pull access

        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1007)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:813)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:268)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:712)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:977)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:941)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error response from daemon: repository eclipse-che/workspacejvuc8i8is9zcdsjr_machine9doqmbeyb2mc16xm_factorycheck_dev-machine not f
ound: does not exist or no pull access

        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:361)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:785)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:949)
        ... 11 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Error response from daemon: repository eclipse-che/workspacejvuc8i8is9zcdsjr_machine9doqmbeyb2mc16xm_factoryc
heck_dev-machine not found: does not exist or no pull access

        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1337)
        at org.eclipse.che.plugin.docker.client.DockerConnector.createContainer(DockerConnector.java:1088)
        at com.codenvy.swarm.client.SwarmDockerConnector.createContainer(SwarmDockerConnector.java:106)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:571)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:306)
        ... 13 common frames omitted
```
</details>

![screen_after_first_unsuccessful_attempt__cdwindow-b453f23e-87fd-4745-b4ae-eafc705805e4](https://cloud.githubusercontent.com/assets/1636620/25478317/53781bc0-2b49-11e7-96a7-537ac8335737.png)

**Reproduction Steps:**

**Codenvy version:**    5.9.0-SaaS
**Docker version:** 17.04.0-ce

**Comment by mmorhun** [comment]
Actually it isn't a regression, it is another problem, but I believe that workaround with retry will help
