### ISSUE TITLE
It is not possible to modify blacklist of emails for self-registration without rebuilding from sources

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#2183]
Del

**Comment by skryzhny** [comment]
Tried to set property `emailvalidator.blacklistfile=/opt/codenvy-data/conf/email-blacklist.lst` and got this error:
<details>

```
2017-05-24 08:46:36,652[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 4733] - Exception sending context initialized event to listener instance of class org.eclipse.che.inject.CheBootstrap
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to java.lang.String annotated with @com.google.inject.name.Named(value=emailvalidator.blacklistfile) was already configured at com.codenvy.auth.sso.server.BearerSecurityModule.configure(BearerSecurityModule.java:35).
  at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperty(CheBootstrap.java:388) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.eclipse.che.inject.CheBootstrap$ExtConfiguration)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-05-24 08:46:36,734[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 4733] - Exception sending context initialized event to listener instance of class org.eclipse.che.everrest.ServerContainerInitializeListener
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
        at org.everrest.core.impl.RequestDispatcher.<init>(RequestDispatcher.java:84)
        at org.eclipse.che.everrest.ServerContainerInitializeListener.getEverrestProcessor(ServerContainerInitializeListener.java:166)
        at org.eclipse.che.everrest.ServerContainerInitializeListener.createWsServerEndpointConfig(ServerContainerInitializeListener.java:124)
        at org.eclipse.che.everrest.ServerContainerInitializeListener.contextInitialized(ServerContainerInitializeListener.java:92)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-05-24 08:46:36,734[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5190]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
2017-05-24 08:46:36,735[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5241]     - Context [/api] startup failed due to previous errors
``` 
</details>
Need at least fix that problem.
@skabashnyuk @vkuznyetsov: Should I create another issue for it?

**Comment by skabashnyuk** [comment]
You need to add your  blacklist to cloud-ide-user-mail-blacklist.txt file
