### ISSUE TITLE
The CheckStoppingWsByTimeoutTest selenium test fails while creating test workspace

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2398]
The **CheckStoppingWsByTimeoutTest** test fails while creating a workspace.
Console output:
```
14:55:13 2017-09-05 11:55:13,260[pool-2-thread-2]  [INFO ] [o.e.c.s.core.user.TestUserImpl 68]   - User name='user-for-check-ws', password 'Pwd1dohx7n', id='usersygpsi4rb6sft75s' has been created
14:55:19 2017-09-05 11:55:19,249[pool-2-thread-1]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 170]  - Dependencies injection in org.eclipse.che.selenium.workspaces.CheckStopStartWsTest
14:55:29 2017-09-05 11:55:29,380[onPool-worker-3]  [INFO ] [o.e.c.s.c.w.TestWorkspaceImpl 64]    - Workspace name='workspacexsk6wk' id='workspacers0jjd8um85me7pl' has been created.
14:55:29 Sep 05, 2017 11:55:29 AM org.openqa.selenium.remote.ProtocolHandshake createSession
14:55:29 INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
14:55:29 Sep 05, 2017 11:55:29 AM org.openqa.selenium.remote.ProtocolHandshake createSession
14:55:29 INFO: Detected dialect: OSS
14:55:29 2017-09-05 11:55:29,946[onPool-worker-3]  [ERROR] [o.e.c.s.c.w.TestWorkspaceImpl 68]    - Workspace name='workspace00v7fk' start failed.
14:55:29 org.eclipse.che.api.core.NotFoundException: Workspace with name 'workspace00v7fk' in namespace 'user-for-check-ws' doesn't exist
14:55:29 	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:247)
14:55:29 	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:152)
14:55:29 	at org.eclipse.che.selenium.core.client.TestWorkspaceServiceClient.getByName(TestWorkspaceServiceClient.java:92)
14:55:29 	at org.eclipse.che.selenium.core.client.TestWorkspaceServiceClient.waitStatus(TestWorkspaceServiceClient.java:136)
14:55:29 	at org.eclipse.che.selenium.core.client.TestWorkspaceServiceClient.start(TestWorkspaceServiceClient.java:189)
14:55:29 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceImpl.lambda$new$1(TestWorkspaceImpl.java:62)
14:55:29 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
14:55:29 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
14:55:29 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
14:55:29 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
14:55:29 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
14:55:29 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
14:55:29 2017-09-05 11:55:29,953[pool-2-thread-2]  [ERROR] [.e.c.s.c.i.SeleniumTestHandler 174]  - Failed to inject fields in com.codenvy.selenium.workspaces.CheckStoppingWsByTimeoutTest
14:55:29 com.google.inject.ProvisionException: Unable to provision, see the following errors:
14:55:29 
14:55:29 1) Error injecting com.codenvy.selenium.workspaces.CheckStoppingWsByTimeoutTest using org.eclipse.che.selenium.core.workspace.TestWorkspaceInjector@27eb28d3.
14:55:29  Reason: java.lang.RuntimeException: Failed to instantiate workspace in com.codenvy.selenium.workspaces.CheckStoppingWsByTimeoutTest
14:55:29   while locating com.codenvy.selenium.workspaces.CheckStoppingWsByTimeoutTest
14:55:29 
14:55:29 1 error
14:55:29 	at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:486)
14:55:29 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:67)
14:55:29 	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:987)
14:55:29 	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.injectDependencies(SeleniumTestHandler.java:196)
14:55:29 	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.beforeInvocation(SeleniumTestHandler.java:171)
14:55:29 	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84)
14:55:29 	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
14:55:29 	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:603)
14:55:29 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:531)
14:55:29 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
14:55:29 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
14:55:29 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
14:55:29 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
14:55:29 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
14:55:29 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
14:55:29 	at java.lang.Thread.run(Thread.java:745)
14:55:29 Caused by: java.lang.RuntimeException: Failed to instantiate workspace in com.codenvy.selenium.workspaces.CheckStoppingWsByTimeoutTest
14:55:29 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceInjector.injectMembers(TestWorkspaceInjector.java:69)
14:55:29 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:140)
14:55:29 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
14:55:29 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
14:55:29 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
14:55:29 	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
14:55:29 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
14:55:29 	... 14 common frames omitted
14:55:29 Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Workspace name='workspace00v7fk' start failed.
14:55:29 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
14:55:29 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
14:55:29 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceImpl.await(TestWorkspaceImpl.java:85)
14:55:29 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceInjector.injectMembers(TestWorkspaceInjector.java:63)
14:55:29 	... 20 common frames omitted
14:55:29 Caused by: java.lang.IllegalStateException: Workspace name='workspace00v7fk' start failed.
14:55:29 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceImpl.lambda$new$1(TestWorkspaceImpl.java:78)
14:55:29 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
14:55:29 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
14:55:29 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
14:55:29 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
14:55:29 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
14:55:29 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
14:55:29 Caused by: org.eclipse.che.api.core.NotFoundException: Workspace with name 'workspace00v7fk' in namespace 'user-for-check-ws' doesn't exist
14:55:29 	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:247)
14:55:29 	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:152)
14:55:29 	at org.eclipse.che.selenium.core.client.TestWorkspaceServiceClient.getByName(TestWorkspaceServiceClient.java:92)
14:55:29 	at org.eclipse.che.selenium.core.client.TestWorkspaceServiceClient.waitStatus(TestWorkspaceServiceClient.java:136)
14:55:29 	at org.eclipse.che.selenium.core.client.TestWorkspaceServiceClient.start(TestWorkspaceServiceClient.java:189)
14:55:29 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceImpl.lambda$new$1(TestWorkspaceImpl.java:62)
14:55:29 	... 6 common frames omitted
14:55:29 2017-09-05 11:55:29,954[pool-2-thread-2]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 212]  - Processing @PreDestroy annotation in com.codenvy.selenium.workspaces.CheckStoppingWsByTimeoutTest
14:55:30 2017-09-05 11:55:30,018[pool-2-thread-2]  [INFO ] [o.e.c.s.core.user.TestUserImpl 119]  - User name='user-for-check-ws', id='usersygpsi4rb6sft75s' removed
```

**Comment by dmytro-ndp** [comment]
Should be fixed by issue https://github.com/eclipse/che/issues/6298
