### ISSUE TITLE
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]

### ISSUE THREAD

**Issue by juan19xx** [codenvy/codenvy#2624]
Hi,
Do you know why I get this exception:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
When I run my project?.
I use this command: mvn -f ${current.project.path} clean install && scp /projects/gestinodev/target/*.war $TOMCAT_HOME/webapps/ROOT.war && $TOMCAT_HOME/bin/catalina.sh jpda run
It was working ok all day, and suddenly it stopped working, I've been using this command for like a year.
I add the log of the console:
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building electro system Maven Webapp 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.lowagie:itext:jar:2.1.7.js2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.olap4j:olap4j:jar:0.9.7.309-JS-3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ROOT ---
[INFO] Deleting /projects/gestinodev/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ROOT ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 21 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ ROOT ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 918 source files to /projects/gestinodev/target/classes
[WARNING] error reading /home/user/.m2/repository/org/olap4j/olap4j/0.9.7.309-JS-3/olap4j-0.9.7.309-JS-3.jar; error in opening zip file
[WARNING] error reading /home/user/.m2/repository/org/olap4j/olap4j/0.9.7.309-JS-3/olap4j-0.9.7.309-JS-3.jar; error in opening zip file
[WARNING] /projects/gestinodev/src/main/java/buket/library/Utilities/WebCfdiConnection.java:[2,50] com.sun.org.apache.xerces.internal.parsers.DOMParser is internal proprietary API and may be removed in a future release
[WARNING] /projects/gestinodev/src/main/java/buket/library/Utilities/WebCfdiConnection.java:[71,37] sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
[WARNING] /projects/gestinodev/src/main/java/buket/library/Utilities/WebCfdiConnection.java:[116,13] com.sun.org.apache.xerces.internal.parsers.DOMParser is internal proprietary API and may be removed in a future release
[WARNING] /projects/gestinodev/src/main/java/buket/library/Utilities/WebCfdiConnection.java:[116,36] com.sun.org.apache.xerces.internal.parsers.DOMParser is internal proprietary API and may be removed in a future release
[WARNING] /projects/gestinodev/src/main/java/buket/library/Utilities/WebCfdiConnection.java:[210,13] com.sun.org.apache.xerces.internal.parsers.DOMParser is internal proprietary API and may be removed in a future release
[WARNING] /projects/gestinodev/src/main/java/buket/library/Utilities/WebCfdiConnection.java:[210,36] com.sun.org.apache.xerces.internal.parsers.DOMParser is internal proprietary API and may be removed in a future release
[WARNING] /projects/gestinodev/src/main/java/buket/library/controllers/SalesController.java:[6273,52] sun.misc.BASE64Decoder is internal proprietary API and may be removed in a future release
[WARNING] /projects/gestinodev/src/main/java/buket/library/controllers/SalesController.java:[6285,61] sun.misc.BASE64Decoder is internal proprietary API and may be removed in a future release
[WARNING] /projects/gestinodev/src/main/java/buket/library/views/SDownPaymentView.java: Some input files use or override a deprecated API.
[WARNING] /projects/gestinodev/src/main/java/buket/library/views/SDownPaymentView.java: Recompile with -Xlint:deprecation for details.
[WARNING] /projects/gestinodev/src/main/java/buket/library/dao/impl/SitePageElementsDaoImpl.java: Some input files use unchecked or unsafe operations.
[WARNING] /projects/gestinodev/src/main/java/buket/library/dao/impl/SitePageElementsDaoImpl.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ROOT ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /projects/gestinodev/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ ROOT ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ ROOT ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-war-plugin:2.2:war (default-war) @ ROOT ---
[INFO] Packaging webapp
[INFO] Assembling webapp [ROOT] in [/projects/gestinodev/target/ROOT]
[INFO] Processing war project
[INFO] Copying webapp resources [/projects/gestinodev/src/main/webapp]
[INFO] Webapp assembled in [830 msecs]
[INFO] Building war: /projects/gestinodev/target/ROOT.war
[INFO] WEB-INF/web.xml already added, skipping
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ ROOT ---
[INFO] Installing /projects/gestinodev/target/ROOT.war to /home/user/.m2/repository/ROOT/ROOT/1.0-SNAPSHOT/ROOT-1.0-SNAPSHOT.war
[INFO] Installing /projects/gestinodev/pom.xml to /home/user/.m2/repository/ROOT/ROOT/1.0-SNAPSHOT/ROOT-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.323 s
[INFO] Finished at: 2018-02-14T22:51:51+00:00
[INFO] Final Memory: 24M/256M
[INFO] ------------------------------------------------------------------------
Listening for transport dt_socket at address: 8000
14-Feb-2018 22:51:52.874 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.24
14-Feb-2018 22:51:52.876 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jul 1 2015 20:19:55 UTC
14-Feb-2018 22:51:52.877 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.24.0
14-Feb-2018 22:51:52.877 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
14-Feb-2018 22:51:52.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-693.17.1.el7.x86_64
14-Feb-2018 22:51:52.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
14-Feb-2018 22:51:52.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
14-Feb-2018 22:51:52.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
14-Feb-2018 22:51:52.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
14-Feb-2018 22:51:52.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/user/tomcat8
14-Feb-2018 22:51:52.881 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/user/tomcat8
14-Feb-2018 22:51:52.882 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/user/tomcat8/conf/logging.properties
14-Feb-2018 22:51:52.882 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
14-Feb-2018 22:51:52.883 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms256m
14-Feb-2018 22:51:52.883 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
14-Feb-2018 22:51:52.884 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC
14-Feb-2018 22:51:52.884 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseStringDeduplication
14-Feb-2018 22:51:52.885 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:/dev/./urandom
14-Feb-2018 22:51:52.885 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -agentlib:jdwp=transport=dt_socket,address=localhost:8000,server=y,suspend=n
14-Feb-2018 22:51:52.886 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/home/user/tomcat8/endorsed
14-Feb-2018 22:51:52.886 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/user/tomcat8
14-Feb-2018 22:51:52.888 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/user/tomcat8
14-Feb-2018 22:51:52.888 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/user/tomcat8/temp
14-Feb-2018 22:51:52.889 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
14-Feb-2018 22:51:53.052 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
14-Feb-2018 22:51:53.075 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
14-Feb-2018 22:51:53.088 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
14-Feb-2018 22:51:53.090 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
14-Feb-2018 22:51:53.094 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1135 ms
14-Feb-2018 22:51:53.147 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
14-Feb-2018 22:51:53.147 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.24
14-Feb-2018 22:51:53.246 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/user/tomcat8/webapps/ROOT.war
14-Feb-2018 22:51:53.347 INFO [localhost-startStop-1] org.apache.catalina.startup.ExpandWar.expand An expanded directory [/home/user/tomcat8/webapps/ROOT] was found with a last modified time that did not match the associated WAR. It will be deleted.
14-Feb-2018 22:51:55.156 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@51a36943]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4845)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4975)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@7097ddf1]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:106)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139)
	at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:699)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 13 more
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: error in opening zip file
	at org.apache.catalina.webresources.JarResourceSet.initInternal(JarResourceSet.java:96)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	... 16 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at org.apache.catalina.webresources.JarResourceSet.initInternal(JarResourceSet.java:88)
	... 17 more
 
14-Feb-2018 22:51:55.160 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive /home/user/tomcat8/webapps/ROOT.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 
14-Feb-2018 22:51:55.162 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/user/tomcat8/webapps/ROOT.war has finished in 1,915 ms
14-Feb-2018 22:51:55.166 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
14-Feb-2018 22:51:55.180 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
14-Feb-2018 22:51:55.182 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 2086 ms

**Comment by cecilcosta** [comment]
Have you found the solution?

**Comment by juan19xx** [comment]
That happened because of a depency in maven, the url wasnt working, what I did was replace the libraries in the maven path, dont remember the maven path that holds the libraries

**Comment by abhishek-tayal** [comment]
If I am deploying my war file in my local tomcat server it is working fine but when I am deploying on my VPS Server it is throwing me this error:
FAIL - Application at context path /projectname could not be started
FAIL - Encountered exception org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/projectname]]

Kindly help me out.

**Comment by juan19xx** [comment]
Maybe it has something to do with a dependency in your pom file, in my
project the dependency I had problem was commons loggin, after I removed
that depebdency it worked. Check your dependencies to see if you have a
problem with any of them.

**Comment by abijotgupta** [comment]
Have you find the solution? Same type of problem I'm facing while working with servlets.

**Comment by AnqiKang** [comment]
I got this error and i solved it after checking  my application local DB connection  username and password,  and EC2 DB username and password. after making these 2 BD use the same user, i successfully deployed to Tomcat.

**Comment by onkarshinde131097** [comment]
I found my issue.
My lib folder was outside the WebContent folder...
I copied it inside WebContent/WEB-INF and everything is working now

**Comment by himanidadem** [comment]
> If I am deploying my war file in my local tomcat server it is working fine but when I am deploying on my VPS Server it is throwing me this error: FAIL - Application at context path /projectname could not be started FAIL - Encountered exception org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/projectname]]
> 
> Kindly help me out.

Please tell me if you found the solution. Pleaseeeeeeeeeeeee

**Comment by Arthursilva12** [comment]
Excluindo a pasta ".m2" em user no seu computador, possivelmente ajuda
