### ISSUE TITLE
Language Server for PHP not work

### ISSUE THREAD

**Issue by filips123** [codenvy/codenvy#2683]
I am using online version of Codenvy (https://codenvy.io/). I created new PHP workspace from default PHP stack (`eclipse/php`). I created new project and added new PHP file (`hello.php`). If I open it, it display popup "Initializing Language Server for hello.php". After about 15 seconds, it display red popup "Initializing Language Server for hello.php". If I then try to use Language Server features, it doesn't work.

I deleted and created few more workspaces, but in all is the same error. I also have old PHP workspace and it works, but I want to replace it with new.

PHP Language Server agent is enabled.

**First popup:**
![Initializing Language Server Popup](https://user-images.githubusercontent.com/16626308/41166320-3b577fe4-6b40-11e8-9988-bf408debcb84.png)

**Second popup:**
![Initializing Language Server error](https://user-images.githubusercontent.com/16626308/41166400-72b8e220-6b40-11e8-8cd8-0d0523cd79f7.png)

**Reproduction Steps:**
1. Open Codenvy (https://codenvy.io/) and log in.
2. Create new workspace from default PHP stack and start it.
3. Create PHP project.
4. Add new PHP file.
5. Open this PHP file.

**Logs:**
```
[STDOUT] 2018-06-08 16:04:27,639[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: java.io.IOException: Stream closed
[STDOUT] java.lang.RuntimeException: java.io.IOException: Stream closed
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:122)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:65)
[STDOUT] 	at com.sun.proxy.$Proxy80.initialize(Unknown Source)
[STDOUT] 	at org.eclipse.che.api.languageserver.registry.ServerInitializerImpl.initialize(ServerInitializerImpl.java:117)
[STDOUT] 	at org.eclipse.che.api.languageserver.registry.LanguageServerRegistryImpl.initialize(LanguageServerRegistryImpl.java:124)
[STDOUT] 	at org.eclipse.che.api.languageserver.service.LanguageServerInitializationHandler.lambda$new$0(LanguageServerInitializationHandler.java:37)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToOne.lambda$withFunction$0(FunctionConfiguratorOneToOne.java:75)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:328)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:315)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:212)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:51)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] Caused by: java.io.IOException: Stream closed
[STDOUT] 	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
[STDOUT] 	at java.io.OutputStream.write(OutputStream.java:116)
[STDOUT] 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[STDOUT] 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:65)
[STDOUT] 	... 16 common frames omitted

[STDOUT] 2018/06/08 16:07:15 Failed to send websocket message: , due to occurred error websocket: close sent
[STDOUT] 2018/06/08 16:07:15 Error occurs on sending ping message to websocket. websocket: close sent
```

**Codenvy version:**
Online Codenvy (https://codenvy.io/) - 5.22.1

**Comment by pascal-linux** [comment]
I have the same problem, it is such a pity. 
Codenvy and Eclipse Che looks incredibly promising - but if php (code completion and templates) are not supported it does not help me.
I think this is really a severe bug for all PHP developers who use or intend to use this IDE.

**Comment by filips123** [comment]
**This will not work. See [my newer comment](https://github.com/codenvy/codenvy/issues/2683#issuecomment-418457988).**

---

I added the following line to `~/.bashrc`:

```bash
(cd /home/user/che/ls-php/php-language-server && composer install) &> /dev/null
```

It should install language server when user logs in. Note that it sometimes works and sometimes not.

**Comment by RolandSM** [comment]
Hey, sorry but not working for me...

**Comment by filips123** [comment]
Other "solution" that may work is to run [PHP Language Server installation script](https://github.com/eclipse/che/blob/master/agents/ls-php/src/main/resources/installers/5.4.0/org.eclipse.che.ls.php.script.sh) from Eclipse Che remository. If this not works, try to delete `/home/user/che/ls-php/` and then run script.

```bash
rm /home/user/che/ls-php/
wget https://raw.githubusercontent.com/eclipse/che/master/agents/ls-php/src/main/resources/installers/5.4.0/org.eclipse.che.ls.php.script.sh
bash org.eclipse.che.ls.php.script.sh
rm org.eclipse.che.ls.php.script.sh
```

If this also not work, we have to wait for offical fix. 😢

**Comment by dragonares5** [comment]
Thank you @filips123 , removing ` /home/user/che/ls-php/` folder and executing the script worked for me.

**Comment by dimaldim** [comment]
Anyone with same problem again? I've tried @filips123 way, but it's not working for me.

**Comment by filips123** [comment]
@dimaldim Try few more times and restart workspace. My solution sometimes not works and you should try it few more times.

We still have to wait for official fix.

**Comment by filips123** [comment]
@riuvshin @eivantsov Is there official fix that always works?

**Comment by dimaldim** [comment]
@filips123, I've found another solution based on your one. With wget you download 5.4.0 version, if you download 5.3.7 and bash the script, then the language server is loaded and for now is working properly :)

**Comment by ghost** [comment]
Hello. Any workaround? The editor is unusable this way.

**Comment by filips123** [comment]
@adiwebdev Try my solution (https://github.com/codenvy/codenvy/issues/2683#issuecomment-418457988). If it doesn't work try to use other versions (as suggested in later comments).

**Comment by kde99** [comment]
Just registered and having the same. Any fix so far (tried that comment and still nothing)? It's kinda surreal that there is no fix for over a year now...

**Comment by filips123** [comment]
@kde99 Try my comment multiple times, restart workspace, recreate it and try some similar steps. Also try some variations of my comment (see other comments).
