### ISSUE TITLE
On beta in logs [ERROR] [m.b.WorkspaceFsBackupScheduler 84] - Machine machine???? is not found

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#454]
```
2016-06-01 19:28:25,486[aceManager-3678]  [INFO ] [o.e.c.a.m.s.MachineManager 856]      - Destroying machine [ws = workspace6ygna7gv2o7ev1v9: env = wksp-a4vc: machine name = ws-machine: machine id = machineqawy6p8d9j4frpy4]
2016-06-01 19:28:25,492[pScheduler-6452]  [ERROR] [m.b.WorkspaceFsBackupScheduler 84]   - Machine machineqawy6p8d9j4frpy4 is not found
org.eclipse.che.api.core.NotFoundException: Machine machineqawy6p8d9j4frpy4 is not found
	at org.eclipse.che.api.machine.server.MachineRegistry.getInstance(MachineRegistry.java:114) ~[che-core-api-machine-4.2.3.jar:4.2.3]
	at org.eclipse.che.api.machine.server.MachineManager.getInstance(MachineManager.java:439) ~[che-core-api-machine-4.2.3.jar:4.2.3]
	at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.backupWorkspaceInMachine(WorkspaceFsBackupScheduler.java:96) ~[codenvy-machine-hosted-4.2.3.jar:4.2.3]
	at com.codenvy.machine.backup.WorkspaceFsBackupScheduler.lambda$scheduleBackup$0(WorkspaceFsBackupScheduler.java:80) ~[codenvy-machine-hosted-4.2.3.jar:4.2.3]
	at com.codenvy.machine.backup.WorkspaceFsBackupScheduler$$Lambda$134/1754240632.run(Unknown Source) [codenvy-machine-hosted-4.2.3.jar:4.2.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

It looks like we got list of machines to do scheduled backup and while backuping other machines this machine went to 'destroying' state.
We need to check again just before doing actual backup OR change loglevel from ERROR to WARNING or INFO.

**Comment by mmorhun** [comment]
Fixed
