### ISSUE TITLE
Issue with snapshots

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#541]
we've found following stack traces:
```
Caused by: java.lang.NullPointerException: null
<------>at com.codenvy.api.dao.mongo.SnapshotImplCodec.decode(SnapshotImplCodec.java:92) ~[codenvy-hosted-platform-api-impl-4.6.0.jar:4.6.0]
<------>at com.codenvy.api.dao.mongo.SnapshotImplCodec.decode(SnapshotImplCodec.java:39) ~[codenvy-hosted-platform-api-impl-4.6.0.jar:4.6.0]
<------>at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:48) ~[mongo-java-driver-3.2.1.jar:na]
<------>at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:53) ~[mongo-java-driver-3.2.1.jar:na]
```

**Comment by mkuznyetsov** [comment]
It needs mongo script to update existing snapshots:
```
db = db.getSiblingDB('organization');
db.snapshots.update({}, {$rename:{"isDev":"dev"}}, false, true);
```
