### ISSUE TITLE
Codenvy beta.codenvy.com error: o.e.c.a.c.u.CompositeLineConsumer - An error occurred while writing line to the line consumer org.eclipse.che.api.core.util.FileLineConsumer

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#587]
I have a lot of emails with these ERRORS

```
2016-08-16 07:38:14,132[iConnector-1970]  [ERROR] [.c.a.c.u.CompositeLineConsumer 47]   - An error occurred while writing line to the line consumer org.eclipse.che.api.core.util.FileLineConsumer@34191951
java.io.IOException: Stream closed
    at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116) ~[na:1.8.0_45]
    at java.io.BufferedWriter.write(BufferedWriter.java:221) ~[na:1.8.0_45]
    at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_45]
    at org.eclipse.che.api.core.util.FileLineConsumer.writeLine(FileLineConsumer.java:38) ~[che-core-api-core-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.core.util.CompositeLineConsumer.writeLine(CompositeLineConsumer.java:45) ~[che-core-api-core-4.6.2.jar:4.6.2]
    at org.eclipse.che.plugin.docker.machine.DockerInstance.lambda$saveToSnapshot$1(DockerInstance.java:234) [che-plugin-docker-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.plugin.docker.machine.DockerInstance$$Lambda$255/2128258486.updateProgress(Unknown Source) [che-plugin-docker-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.plugin.docker.client.DockerConnector.lambda$push$1(DockerConnector.java:916) [che-plugin-docker-client-4.6.2.jar:4.6.2]
    at org.eclipse.che.plugin.docker.client.DockerConnector$$Lambda$256/1233904.call(Unknown Source) [che-plugin-docker-client-4.6.2.jar:4.6.2]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

And this one

```
2016-08-15 18:04:56,159[aceManager-2474]  [ERROR] [.c.a.c.u.CompositeLineConsumer 47]   - An error occurred while writing line to the line consumer org.eclipse.che.api.core.util.FileLineConsumer@21ed9a30
java.io.IOException: Stream closed
    at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116) ~[na:1.8.0_45]
    at java.io.BufferedWriter.write(BufferedWriter.java:221) ~[na:1.8.0_45]
    at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_45]
    at org.eclipse.che.api.core.util.FileLineConsumer.writeLine(FileLineConsumer.java:38) ~[che-core-api-core-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.core.util.CompositeLineConsumer.writeLine(CompositeLineConsumer.java:45) ~[che-core-api-core-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:411) [che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager$$Lambda$155/411821061.createInstance(Unknown Source) [che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:340) [che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:166) [che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) [che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) [che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) [che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:533) [che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$152/40631207.run(Unknown Source) [che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-4.6.2.jar:4.6.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

Codenvy version: 4.6.2
OS and version: Centos 7.2

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: No - it's random

**Comment by skryzhny** [comment]
Got new type of exceptions:
```
2016-09-19 07:28:21,738[essManager-4701]  [ERROR] [.c.a.c.u.CompositeLineConsumer 47]   - An error occurred while writing line to the line consumer org.eclipse.che.api.core.util.FileLineConsumer@5aedd056
java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.8.0_45]
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:215) ~[na:1.8.0_45]
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[na:1.8.0_45]
        at java.nio.channels.Channels.writeFully(Channels.java:101) ~[na:1.8.0_45]
        at java.nio.channels.Channels.access$000(Channels.java:61) ~[na:1.8.0_45]
        at java.nio.channels.Channels$1.write(Channels.java:174) ~[na:1.8.0_45]
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[na:1.8.0_45]
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) ~[na:1.8.0_45]
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295) ~[na:1.8.0_45]
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141) ~[na:1.8.0_45]
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229) ~[na:1.8.0_45]
        at java.io.BufferedWriter.flush(BufferedWriter.java:254) ~[na:1.8.0_45]
        at org.eclipse.che.api.core.util.FileLineConsumer.writeLine(FileLineConsumer.java:41) ~[che-core-api-core-4.7.2.jar:4.7.2]
        at org.eclipse.che.api.core.util.CompositeLineConsumer.writeLine(CompositeLineConsumer.java:45) ~[che-core-api-core-4.7.2.jar:4.7.2]
        at org.eclipse.che.plugin.docker.machine.LogMessagePrinter.process(LogMessagePrinter.java:44) [che-plugin-docker-machine-4.7.2.jar:4.7.2]
        at org.eclipse.che.plugin.docker.machine.LogMessagePrinter.process(LogMessagePrinter.java:26) [che-plugin-docker-machine-4.7.2.jar:4.7.2]
        at org.eclipse.che.plugin.docker.client.LogMessagePumper.start(LogMessagePumper.java:80) [che-plugin-docker-client-4.7.2.jar:4.7.2]
        at org.eclipse.che.plugin.docker.client.DockerConnector.startExec(DockerConnector.java:543) [che-plugin-docker-client-4.7.2.jar:4.7.2]
        at org.eclipse.che.plugin.docker.machine.DockerProcess.start(DockerProcess.java:108) [che-plugin-docker-machine-4.7.2.jar:4.7.2]
        at org.eclipse.che.api.environment.server.MachineProcessManager.lambda$exec$0(MachineProcessManager.java:121) [che-core-api-workspace-4.7.2.jar:4.7.2]
        at org.eclipse.che.api.environment.server.MachineProcessManager$$Lambda$187/1507701160.run(Unknown Source) [che-core-api-workspace-4.7.2.jar:4.7.2]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-4.7.2.jar:4.7.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

And
```
2016-09-19 17:32:25,767[paceManager-177]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 610]   - Launching 'org.eclipse.che.ws-agent' agent
2016-09-19 17:32:28,412[cessManager-145]  [ERROR] [.c.a.c.u.CompositeLineConsumer 47]   - An error occurred while writing line to the line consumer org.eclipse.che.api.core.util.FileLineConsumer@287c0970
java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.8.0_45]
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:215) ~[na:1.8.0_45]
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[na:1.8.0_45]
        at java.nio.channels.Channels.writeFully(Channels.java:101) ~[na:1.8.0_45]
        at java.nio.channels.Channels.access$000(Channels.java:61) ~[na:1.8.0_45]
        at java.nio.channels.Channels$1.write(Channels.java:174) ~[na:1.8.0_45]
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[na:1.8.0_45]
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) ~[na:1.8.0_45]
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295) ~[na:1.8.0_45]
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141) ~[na:1.8.0_45]
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229) ~[na:1.8.0_45]
        at java.io.BufferedWriter.flush(BufferedWriter.java:254) ~[na:1.8.0_45]
        at org.eclipse.che.api.core.util.FileLineConsumer.writeLine(FileLineConsumer.java:41) ~[che-core-api-core-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.api.core.util.CompositeLineConsumer.writeLine(CompositeLineConsumer.java:45) ~[che-core-api-core-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.plugin.docker.machine.LogMessagePrinter.process(LogMessagePrinter.java:44) [che-plugin-docker-machine-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.plugin.docker.machine.LogMessagePrinter.process(LogMessagePrinter.java:26) [che-plugin-docker-machine-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.plugin.docker.client.LogMessagePumper.start(LogMessagePumper.java:80) [che-plugin-docker-client-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.plugin.docker.client.DockerConnector.startExec(DockerConnector.java:544) [che-plugin-docker-client-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.plugin.docker.machine.DockerProcess.start(DockerProcess.java:108) [che-plugin-docker-machine-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.api.environment.server.MachineProcessManager.lambda$exec$0(MachineProcessManager.java:121) [che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.api.environment.server.MachineProcessManager$$Lambda$259/2138790081.run(Unknown Source) [che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M1.jar:5.0.0-M1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by TylerJewell** [comment]
@skryzhny - is this still actual?

**Comment by mmorhun** [comment]
Fixed
