### ISSUE TITLE
Codenvy beta.codenvy.com error: o.e.c.a.c.n.EventService - null

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#602]
I'm constantly getting these errors in emails, 67 total for last 2 month
Most of them have no stacktrace, like:
```
2016-08-17 16:22:57,051[aceManager-3795]  [ERROR] [o.e.c.a.c.n.EventService 107]        - null
java.lang.NullPointerException: null
```
But sometime I got stacktrace like:
```
2016-08-11 11:43:06,046[spaceManager-10]  [ERROR] [o.e.c.a.c.n.EventService 107]        - null
java.lang.NullPointerException: null
	at com.codenvy.auth.sso.client.MachineSessionInvalidator.onEvent(MachineSessionInvalidator.java:56) ~[codenvy-hosted-sso-client-4.6.2.jar:4.6.2]
	at com.codenvy.auth.sso.client.MachineSessionInvalidator.onEvent(MachineSessionInvalidator.java:35) ~[codenvy-hosted-sso-client-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:105) ~[che-core-api-core-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.publishEvent(WorkspaceRuntimes.java:368) [che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.destroyRuntime(WorkspaceRuntimes.java:424) [che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:294) [che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStop$3(WorkspaceManager.java:578) [che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$226/862942332.run(Unknown Source) [che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-4.6.2.jar:4.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```
And
```
2016-07-21 11:19:30,974[aceManager-3349]  [ERROR] [o.e.c.a.c.n.EventService 107]        - null
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106) ~[na:1.8.0_45]
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097) ~[na:1.8.0_45]
	at com.codenvy.auth.sso.client.SessionStore.removeSessionByToken(SessionStore.java:58) ~[codenvy-hosted-sso-client-4.4.2.jar:4.4.2]
	at com.codenvy.auth.sso.client.MachineSessionInvalidator.onEvent(MachineSessionInvalidator.java:55) ~[codenvy-hosted-sso-client-4.4.2.jar:4.4.2]
	at com.codenvy.auth.sso.client.MachineSessionInvalidator.onEvent(MachineSessionInvalidator.java:35) ~[codenvy-hosted-sso-client-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:105) ~[che-core-api-core-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.publishEvent(WorkspaceRuntimes.java:368) [che-core-api-workspace-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.destroyRuntime(WorkspaceRuntimes.java:429) [che-core-api-workspace-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:294) [che-core-api-workspace-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStop$3(WorkspaceManager.java:596) [che-core-api-workspace-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$160/1112315615.run(Unknown Source) [che-core-api-workspace-4.4.2.jar:4.4.2]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-4.4.2.jar:4.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```
And
```
2016-07-19 14:53:11,224[ineManager-2159]  [ERROR] [o.e.c.a.c.n.EventService 107]        - null
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[na:1.8.0_45]
	at org.eclipse.che.plugin.docker.client.params.CreateExecParams.withContainer(CreateExecParams.java:60) ~[che-plugin-docker-client-4.4.2.jar:4.4.2]
	at org.eclipse.che.plugin.docker.client.params.CreateExecParams.create(CreateExecParams.java:44) ~[che-plugin-docker-client-4.4.2.jar:4.4.2]
	at org.eclipse.che.plugin.docker.client.DockerConnector.createExec(DockerConnector.java:713) ~[che-plugin-docker-client-4.4.2.jar:4.4.2]
	at org.eclipse.che.ide.ext.machine.server.ssh.KeysInjector$1.onEvent(KeysInjector.java:86) ~[che-plugin-machine-ext-server-4.4.2.jar:4.4.2]
	at org.eclipse.che.ide.ext.machine.server.ssh.KeysInjector$1.onEvent(KeysInjector.java:62) ~[che-plugin-machine-ext-server-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:105) ~[che-core-api-core-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:386) [che-core-api-machine-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.machine.server.MachineManager.lambda$null$0(MachineManager.java:261) [che-core-api-machine-4.4.2.jar:4.4.2]
	at org.eclipse.che.api.machine.server.MachineManager$$Lambda$179/1935215.run(Unknown Source) [che-core-api-machine-4.4.2.jar:4.4.2]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-4.4.2.jar:4.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

Reproduction Steps:
Don't know how to reproduce

Expected behavior:
No errors in logs

Observed behavior:
Errors in logs

Codenvy version: 4.5 4.6.2
OS and version: Centos 7.2

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: No
Problem can be reliably reproduced: No - it's random

**Comment by JamesDrummond** [comment]
@skryzhny Is this error still coming up with the new 5.0.0-MX releases?

**Comment by skryzhny** [comment]
Still getting those exceptions mostly:
```
2016-10-05 06:54:34,412[aceManager-1208]  [ERROR] [o.e.c.a.c.n.EventService 107]        - null
java.lang.NullPointerException: null
```
But sometime:
```
2016-10-04 15:46:28,261[paceManager-842]  [ERROR] [o.e.c.a.c.n.EventService 107]        - null
java.lang.NullPointerException: null
	at com.codenvy.auth.sso.client.MachineSessionInvalidator.onEvent(MachineSessionInvalidator.java:56) ~[codenvy-hosted-sso-client-5.0.0-M4.jar:5.0.0-M4]
	at com.codenvy.auth.sso.client.MachineSessionInvalidator.onEvent(MachineSessionInvalidator.java:35) ~[codenvy-hosted-sso-client-5.0.0-M4.jar:5.0.0-M4]
	at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:105) ~[che-core-api-core-5.0.0-M4.jar:5.0.0-M4]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.publishWorkspaceEvent(WorkspaceRuntimes.java:583) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:345) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStop$2(WorkspaceManager.java:663) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
	at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$198/1031630348.run(Unknown Source) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M4.jar:5.0.0-M4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by mkuznyetsov** [comment]
Merged fix https://github.com/codenvy/codenvy/issues/1026
