### ISSUE TITLE
Codenvy beta.codenvy.com error: o.e.c.a.w.s.WorkspaceManager - Restore of workspace ??? failed. Another restore process of the same workspace is in progress

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#604]
I started getting these errors after update to 4.6.2
```
2016-08-18 23:11:54,284[aceManager-4851]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 549]    - Restore of workspace workspacev65h2t2iuq8l1zwr failed. Another restore process of the same workspace is in progress
org.eclipse.che.api.machine.server.exception.MachineException: Restore of workspace workspacev65h2t2iuq8l1zwr failed. Another restore process of the same workspace is in progress
	at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:416) ~[che-core-api-machine-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.machine.server.MachineManager$$Lambda$155/411821061.createInstance(Unknown Source) ~[na:na]
	at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:340) ~[che-core-api-machine-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:166) ~[che-core-api-machine-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:533) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$152/40631207.run(Unknown Source) [che-core-api-workspace-4.6.2.jar:4.6.2]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-4.6.2.jar:4.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Restore of workspace workspacev65h2t2iuq8l1zwr failed. Another restore process of the same workspace is in progress
	at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:128) ~[codenvy-machine-hosted-4.6.2.jar:4.6.2]
	at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:587) ~[che-plugin-docker-machine-4.6.2.jar:4.6.2]
	at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:330) ~[che-plugin-docker-machine-4.6.2.jar:4.6.2]
	at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:379) ~[che-core-api-machine-4.6.2.jar:4.6.2]
	... 12 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Restore of workspace workspacev65h2t2iuq8l1zwr failed. Another restore process of the same workspace is in progress
	at com.codenvy.machine.backup.MachineBackupManager.restoreWorkspaceBackup(MachineBackupManager.java:199) ~[codenvy-machine-hosted-4.6.2.jar:4.6.2]
	at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:119) ~[codenvy-machine-hosted-4.6.2.jar:4.6.2]
	... 15 common frames omitted
```
Or error without stacktrace:
```
2016-08-18 07:30:02,836[aceManager-4290]  [ERROR] [c.c.m.b.MachineBackupManager 198]    - Restore of workspace workspacev65h2t2iuq8l1zwr failed. Another restore process of the same workspace is in progress
```

Reproduction Steps:
Don't know

Expected behavior:
No errors

Observed behavior:
Errors in logs

Codenvy version: 4.6.2
OS and version: Centos 7.2

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: No - it's random

**Comment by skryzhny** [comment]
There no more such errors in logs starting from Aug 28. Probably update to 4.7.0 fixed that.
