### ISSUE TITLE
Activity checker stops working after few hours

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#899]
After few hours of working activity-checker stops doing it's job.

I can find only this exception in timeframe:
```
2016-10-04 17:27:17,031[io-8080-exec-16]  [INFO ] [o.e.c.a.f.s.jpa.JpaFactoryDao 115]   - FactoryDao#getByAttributes #maxItems: 5 #skipCount: 0, #attributes: [{first=creator.userId, second=user***************}]
2016-10-04 17:27:22,494[paceManager-913]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 634]    - 
Exception Description: A signal was attempted before wait() on ConcurrencyManager. This normally means that an attempt was made to 
commit or rollback a transaction before it was started, or to rollback a transaction twice.
org.eclipse.persistence.exceptions.ConcurrencyException: 
Exception Description: A signal was attempted before wait() on ConcurrencyManager. This normally means that an attempt was made to 
commit or rollback a transaction before it was started, or to rollback a transaction twice.
        at org.eclipse.persistence.exceptions.ConcurrencyException.signalAttemptedBeforeWait(ConcurrencyException.java:84) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.helper.ConcurrencyManager.releaseReadLock(ConcurrencyManager.java:468) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.identitymaps.CacheKey.releaseReadLock(CacheKey.java:468) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1044) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:955) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkIdentityMapAccessor.getAndCloneCacheKeyFromParent(UnitOfWorkIdentityMapAccessor.java:209) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkIdentityMapAccessor.getFromIdentityMap(UnitOfWorkIdentityMapAccessor.java:137) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3940) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3894) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.mappings.CollectionMapping.buildElementUnitOfWorkClone(CollectionMapping.java:308) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.mappings.CollectionMapping.buildElementClone(CollectionMapping.java:321) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.queries.MapContainerPolicy.buildCloneForValue(MapContainerPolicy.java:234) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.queries.MapContainerPolicy.addNextValueFromIteratorInto(MapContainerPolicy.java:168) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.mappings.CollectionMapping.buildCloneForPartObject(CollectionMapping.java:223) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.UnitOfWorkQueryValueHolder.buildCloneFor(UnitOfWorkQueryValueHolder.java:60) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:173) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:234) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.indirection.IndirectMap.buildDelegate(IndirectMap.java:118) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.indirection.IndirectMap.getDelegate(IndirectMap.java:367) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.jdk8.IndirectMap.access$000(IndirectMap.java:33) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.jdk8.IndirectMap$1.<init>(IndirectMap.java:54) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.jdk8.IndirectMap.entrySet(IndirectMap.java:53) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.che.api.workspace.server.model.impl.EnvironmentImpl.<init>(EnvironmentImpl.java:68) ~[che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:223) ~[che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:618) ~[che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
        at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$116/1972050829.run(Unknown Source) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M4.jar:5.0.0-M4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Reproduction Steps:**

Just let it run for a while.

**Expected behavior:**

Activity-checker works.

**Observed behavior:**

Activity-checker doesn't work.

**Codenvy version:** Codenvy 5.0.0-M4
**OS and version:** Centos 7.2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: No - it's random

**Comment by skryzhny** [comment]
Got another exception
```
016-10-05 10:03:02,223[nio-8080-exec-1]  [INFO ] [o.e.c.a.f.s.jpa.JpaFactoryDao 115]   - FactoryDao#getByAttributes #maxItems: 5 #skipCount: 0, #attributes: [{first=creator.userId, second=user4qf7fajvk9wzdo1h}]
2016-10-05 10:03:02,338[nio-8080-exec-4]  [WARN ] [c.c.a.s.c.HttpSsoServerClient 67]    - Access token not found or expired.
2016-10-05 10:03:03,831[nio-8080-exec-4]  [WARN ] [c.c.a.s.c.HttpSsoServerClient 67]    - Access token not found or expired.
2016-10-05 10:03:04,361[nio-8080-exec-7]  [WARN ] [c.c.a.s.c.HttpSsoServerClient 67]    - Access token not found or expired.
2016-10-05 10:03:04,820[nio-8080-exec-9]  [WARN ] [.c.a.d.a.AuthenticationDaoImpl 153]  - Token not found in request.
2016-10-05 10:03:05,375[io-8080-exec-14]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2016-10-05 10:03:05
org.eclipse.persistence.exceptions.ConcurrencyException: 
Exception Description: A signal was attempted before wait() on ConcurrencyManager. This normally means that an attempt was made to 
commit or rollback a transaction before it was started, or to rollback a transaction twice.
        at org.eclipse.persistence.exceptions.ConcurrencyException.signalAttemptedBeforeWait(ConcurrencyException.java:84) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.helper.ConcurrencyManager.releaseReadLock(ConcurrencyManager.java:468) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.identitymaps.CacheKey.releaseReadLock(CacheKey.java:468) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1041) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:955) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkIdentityMapAccessor.getAndCloneCacheKeyFromParent(UnitOfWorkIdentityMapAccessor.java:209) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkIdentityMapAccessor.getFromIdentityMap(UnitOfWorkIdentityMapAccessor.java:137) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3940) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3894) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.mappings.CollectionMapping.buildElementUnitOfWorkClone(CollectionMapping.java:308) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.mappings.CollectionMapping.buildElementClone(CollectionMapping.java:321) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.queries.ContainerPolicy.addNextValueFromIteratorInto(ContainerPolicy.java:215) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.mappings.CollectionMapping.buildCloneForPartObject(CollectionMapping.java:223) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.UnitOfWorkQueryValueHolder.buildCloneFor(UnitOfWorkQueryValueHolder.java:60) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:173) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:234) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.indirection.IndirectList.buildDelegate(IndirectList.java:271) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.indirection.IndirectList.getDelegate(IndirectList.java:455) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.persistence.internal.indirection.jdk8.IndirectList.stream(IndirectList.java:171) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
        at org.eclipse.che.api.workspace.server.DtoConverter.asDto(DtoConverter.java:73) ~[che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
        at org.eclipse.che.api.workspace.server.DtoConverter.asDto(DtoConverter.java:62) ~[che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
        at org.eclipse.che.api.workspace.server.WorkspaceService.startById(WorkspaceService.java:290) ~[che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
        at sun.reflect.GeneratedMethodAccessor266.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140) ~[everrest-core-1.13.1.jar:na]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60) ~[everrest-core-1.13.1.jar:na]
        at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306) ~[everrest-core-1.13.1.jar:na]
        at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297) ~[everrest-core-1.13.1.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233) ~[everrest-core-1.13.1.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128) ~[everrest-core-1.13.1.jar:na]
        at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62) ~[everrest-core-1.13.1.jar:na]
        at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120) [everrest-core-1.13.1.jar:na]
        at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61) [everrest-core-1.13.1.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436) [catalina.jar:8.0.32]
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177) [catalina.jar:8.0.32]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.codenvy.auth.sso.client.DefaultTokenHandler.handleValidToken(DefaultTokenHandler.java:65) [codenvy-hosted-sso-client-5.0.0-M4.jar:5.0.0-M4]
        at com.codenvy.api.permission.server.PermissionTokenHandler.handleValidToken(PermissionTokenHandler.java:64) [codenvy-hosted-authorization-5.0.0-M4.jar:5.0.0-M4]
        at com.codenvy.auth.sso.client.LoginFilter.doFilter(LoginFilter.java:120) [codenvy-hosted-sso-client-5.0.0-M4.jar:5.0.0-M4]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.32]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.32]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.32]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.32]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.32]
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [catalina.jar:8.0.32]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.32]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [catalina.jar:8.0.32]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-coyote.jar:8.0.32]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-coyote.jar:8.0.32]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-coyote.jar:8.0.32]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-coyote.jar:8.0.32]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.32]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2016-10-05 10:03:05,833[nio-8080-exec-1]  [WARN ] [c.c.a.s.c.HttpSsoServerClient 67]    - Access token not found or expired.
```
