### ISSUE TITLE
Snapshot creation sometimes fails

### ISSUE THREAD

**Issue by evoevodin** [codenvy/codenvy#903]
Stack trace from beta logs
```
2016-10-03 22:24:46,576[paceManager-325]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 758]    - Snapshot creation failed. Error: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: insert or update on table "snapshot" violates foreign key constraint "fk_snapshot_workspaceid"
  Detail: Key (workspaceid)=(workspaceupfod9z5jokj5jk0) is not present in table "workspace".
Error Code: 0
Call: INSERT INTO SNAPSHOT (ID, CREATIONDATE, DESCRIPTION, ENVNAME, ISDEV, MACHINENAME, TYPE, WORKSPACEID, CONTENT, LOCATION, source_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    bind => [11 parameters bound]
Query: InsertObjectQuery(SnapshotImpl{id='snapshotsp09vx5h6bb8v3mx', type='docker', machineSource=MachineSourceImpl{type='image', location='beta.codenvy.com:5000/machine_snapshot_vun69k1d4id6f2lh:latest@sha256:198506a7ce7a1a7e4383302e9ea3bb391021fff546df8d726c7eaa7fca64f60d', content='null'}, creationDate=1475533445472, isDev=true, description='default', workspaceId='workspaceupfod9z5jokj5jk0', machineName='dev-machine', envName='default'})
org.eclipse.che.api.machine.server.exception.SnapshotException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: insert or update on table "snapshot" violates foreign key constraint "fk_snapshot_workspaceid"
  Detail: Key (workspaceid)=(workspaceupfod9z5jokj5jk0) is not present in table "workspace".
Error Code: 0
Call: INSERT INTO SNAPSHOT (ID, CREATIONDATE, DESCRIPTION, ENVNAME, ISDEV, MACHINENAME, TYPE, WORKSPACEID, CONTENT, LOCATION, source_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    bind => [11 parameters bound]
Query: InsertObjectQuery(SnapshotImpl{id='snapshotsp09vx5h6bb8v3mx', type='docker', machineSource=MachineSourceImpl{type='image', location='beta.codenvy.com:5000/machine_snapshot_vun69k1d4id6f2lh:latest@sha256:198506a7ce7a1a7e4383302e9ea3bb391021fff546df8d726c7eaa7fca64f60d', content='null'}, creationDate=1475533445472, isDev=true, description='default', workspaceId='workspaceupfod9z5jokj5jk0', machineName='dev-machine', envName='default'})
    at org.eclipse.che.api.machine.server.jpa.JpaSnapshotDao.saveSnapshot(JpaSnapshotDao.java:106) ~[che-core-api-machine-5.0.0-M4.jar:5.0.0-M4]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.replaceSnapshot(WorkspaceManager.java:741) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.createSnapshotSync(WorkspaceManager.java:704) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$createSnapshot$0(WorkspaceManager.java:489) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
    at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$238/767726682.run(Unknown Source) [che-core-api-workspace-5.0.0-M4.jar:5.0.0-M4]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M4.jar:5.0.0-M4]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.eclipse.che.api.core.jdbc.jpa.IntegrityConstraintViolationException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: insert or update on table "snapshot" violates foreign key constraint "fk_snapshot_workspaceid"
  Detail: Key (workspaceid)=(workspaceupfod9z5jokj5jk0) is not present in table "workspace".
Error Code: 0
Call: INSERT INTO SNAPSHOT (ID, CREATIONDATE, DESCRIPTION, ENVNAME, ISDEV, MACHINENAME, TYPE, WORKSPACEID, CONTENT, LOCATION, source_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    bind => [11 parameters bound]
Query: InsertObjectQuery(SnapshotImpl{id='snapshotsp09vx5h6bb8v3mx', type='docker', machineSource=MachineSourceImpl{type='image', location='beta.codenvy.com:5000/machine_snapshot_vun69k1d4id6f2lh:latest@sha256:198506a7ce7a1a7e4383302e9ea3bb391021fff546df8d726c7eaa7fca64f60d', content='null'}, creationDate=1475533445472, isDev=true, description='default', workspaceId='workspaceupfod9z5jokj5jk0', machineName='dev-machine', envName='default'})
    at org.eclipse.che.api.core.postgresql.jdbc.jpa.eclipselink.PostgreSqlExceptionHandler.handleException(PostgreSqlExceptionHandler.java:42) ~[codenvy-hosted-api-jdbc-vendor-postgresql-5.0.0-M4.jar:5.0.0-M4]
    at org.eclipse.persistence.internal.sessions.AbstractSession.handleException(AbstractSession.java:3178) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1902) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1790) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:227) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:126) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4263) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1531) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:278) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:134) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:91) ~[guice-persist-4.1.0.jar:na]
    at org.eclipse.che.api.machine.server.jpa.JpaSnapshotDao.saveSnapshot(JpaSnapshotDao.java:98) ~[che-core-api-machine-5.0.0-M4.jar:5.0.0-M4]
    ... 8 common frames omitted
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: insert or update on table "snapshot" violates foreign key constraint "fk_snapshot_workspaceid"
  Detail: Key (workspaceid)=(workspaceupfod9z5jokj5jk0) is not present in table "workspace".
Error Code: 0
Call: INSERT INTO SNAPSHOT (ID, CREATIONDATE, DESCRIPTION, ENVNAME, ISDEV, MACHINENAME, TYPE, WORKSPACEID, CONTENT, LOCATION, source_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    bind => [11 parameters bound]
Query: InsertObjectQuery(SnapshotImpl{id='snapshotsp09vx5h6bb8v3mx', type='docker', machineSource=MachineSourceImpl{type='image', location='beta.codenvy.com:5000/machine_snapshot_vun69k1d4id6f2lh:latest@sha256:198506a7ce7a1a7e4383302e9ea3bb391021fff546df8d726c7eaa7fca64f60d', content='null'}, creationDate=1475533445472, isDev=true, description='default', workspaceId='workspaceupfod9z5jokj5jk0', machineName='dev-machine', envName='default'})
    at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1620) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:900) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:964) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:633) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2055) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:306) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:377) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:803) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
    ... 20 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "snapshot" violates foreign key constraint "fk_snapshot_workspaceid"
  Detail: Key (workspaceid)=(workspaceupfod9z5jokj5jk0) is not present in table "workspace".
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc41.jar:na]
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc41.jar:na]
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc41.jar:na]
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc41.jar:na]
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc41.jar:na]
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365) ```

**Comment by bmicklea** [comment]
@riuvshin  Is this a blocker?  If not shouldn't it be in M6?

**Comment by riuvshin** [comment]
it is not a blocker. we already have PR for that so I will be in M5 tomorrow

**Comment by bmicklea** [comment]
Thanks
